---
title: "Forest Vegetation Events QC"
author: "John Paul Schmit"
date: "5/18/2020"
output: html_document
---

```{r Events_Setup, include=F}
#2.1.0
TotEvents<-nrow(QCEvents) #Total Number of events checked

#2.2.0
Events_No_Protocol<-QCEvents %>% filter(Protocol=="" | is.na(Protocol)) %>% select(Unit_Code, Plot_Name, Event_Year, Protocol)

#2.3.0
Events_Bad_Protocol<-QCEvents %>% filter(Protocol!=""| is.na(Protocol)) %>%
  filter( (Event_Year<2009 & Protocol != "1.0") | (Event_Year==2009 & Protocol != "2.0") |
    (Event_Year %in% 2010:2013 & Protocol != "2.0.1") | (Event_Year==2014 & Protocol != "2.1") |
    (Event_Year %in% 2015:2016 & Protocol != "2.2") | (Event_Year==2017 & Protocol != "2.3") |
    (Event_Year==2018 & Protocol != "2.4") | (Event_Year==2019 & Protocol!= "2.5") |
     (Event_Year==2020:2021 & Protocol!= "2.6") ) %>% 
  select(Unit_Code, Plot_Name, Event_Year, Protocol)

#2.4.0
Events_No_Date<-QCEvents %>% left_join(QCPlots, by=c("Unit_Code","Plot_Name")) %>%
  filter(is.na(Event_Date) | Event_Date< mdy_hm(Install_Date))  %>%
  select(Unit_Code,Plot_Name, Event_Year, Event_Date, Install_Date)

#2.5.0
Events_Bad_Date<-QCEvents %>% filter( month(Event_Date)<4  | month(Event_Date) >9  | ( month(Event_Date)==4 & mday(Event_Date)<15 ) ) %>% 
  select(Unit_Code, Plot_Name, Event_Year, Event_Date)

Events_Bad_Year<-QCEvents %>% filter(Event_Year!=year(Event_Date)) %>% 
  select(Unit_Code, Plot_Name, Event_Date, Event_Year)


#2.6.0
Events_Bad_Unit<-QCEvents %>% 
   filter(!Unit_Code %in% c("ANTI", "CATO", "CHOH", "GWMP", "HAFE", "MANA", "MONO", "NACE", "PRWI", "ROCR", "WOTR")) %>% 
   select(Unit_Code, Plot_Name, Event_Year)

#2.7.0
Events_Bad_Unit_Group<-QCEvents %>% 
   filter(!Unit_Group %in% c("ANTI","BOHE", "BRUN", "CATO", "CUMB", "GREE", "LOHE", "MAHE", "MANA", "MONO", "NACE", "PISC", "POGO","PRWI", "ROCR", 
                            "SHHI","SHIS","TIDE", "WILL", "WOTR")) %>% 
   select(Unit_Group, Plot_Name, Event_Year)

Events_Mismatch_Unit_Group<-QCEvents %>% 
   filter(Unit_Code=="ANTI" & Unit_Group!="ANTI"|
             Unit_Code=="CATO" & Unit_Group !="CATO"|
             Unit_Code=="CHOH" & !Unit_Group %in% c("BRUN", "CUMB", "POGO", "WILL") |
             Unit_Code =="GWMP" & !Unit_Group %in% c("POGO","TIDE") |
             Unit_Code =="HAFE" & !Unit_Group %in% c("BOHE", "LOHE", "MAHE","SHHI", "SHIS")|
             Unit_Code=="MANA" & Unit_Group !="MANA" |
             Unit_Code=="MONO" & Unit_Group !="MONO" |
             Unit_Code=="NACE" & !Unit_Group %in% c("GREE","NACE","PISC")|
             Unit_Code=="PRWI" & Unit_Group !="PRWI" |
             Unit_Code=="ROCR" & Unit_Group !="ROCR" |
             Unit_Code=="WOTR" & Unit_Group!="WOTR"
          ) %>% 
   select(Plot_Name, Unit_Code, Unit_Group, Event_Year)

#2.8.0 Reserved for sub-unit codes

#2.9.0

Events_Missing_Plot<-QCEvents %>% 
  filter(is.na(Plot_Name) | Plot_Name=="" | !Plot_Name %in% QCPlots$Plot_Name) %>% 
  select(Plot_Name, Unit_Code, Event_Year)

#2.10.0
Events_Duplicated<-QCEvents %>% 
  group_by(Unit_Code, Plot_Name, Event_Date) %>% 
  summarise(Event_Count=n()) %>% 
  filter(Event_Count!=1)

#2.11.0
Events_Bad_Panel<-QCEvents %>%
  filter(!Panel %in% 1:4) %>% 
  select(Unit_Code, Plot_Name,Event_Year, Panel)

#2.12.0
Events_Bad_Frame<-QCEvents %>%
  filter(!Frame %in% c("Park","Region")) %>% 
  select(Unit_Code, Plot_Name,Event_Year, Frame)

#2.13.0
Events_Bad_Cycle<-QCEvents %>% 
  filter(!(Cycle==1 & Event_Year %in% 2005:2009) &
         !(Cycle==2 & Event_Year %in% 2010:2013) &
         !(Cycle==3 & Event_Year %in% 2014:2017) &
         !(Cycle==4 & Event_Year %in% 2018:2022)) %>% 
  select(Unit_Code,Plot_Name, Event_Year, Cycle)

#2.14.0
Events_No_Pictures<-QCEvents %>% 
  filter(!PicturesTaken %in% 1) %>% 
  select(Unit_Code, Plot_Name, Event_Year, PicturesTaken)


#2.15.0
Events_No_CWD<-QCEvents %>% 
  filter( (!CWDCheck360 %in% 1) |
          (!CWDCheck120 %in% 1) |
          (!CWDCheck240 %in% 1)) %>% 
  select(Unit_Code, Plot_Name, Event_Year, CWDCheck360, CWDCheck240, CWDCheck120) %>% 
  left_join( QCCWD %>% group_by(Plot_Name, Sample_Year, Transect_Azimuth) %>% summarise(CWD_Pieces=n()) %>%
  pivot_wider(names_from = Transect_Azimuth, id_cols=c(Plot_Name, Sample_Year), values_from= CWD_Pieces, values_fill=0,
              names_prefix="CWD_Pieces") %>% rename(Event_Year=Sample_Year)
  )

#2.16.0
Events_No_Invasive_Early_Detect<-QCEvents %>% 
  filter(!InvasiveEarlyDetect %in% c(0,1)) %>% 
  select(Unit_Code, Plot_Name, Event_Year, InvasiveEarlyDetect)

#2.17.0
Events_No_Rare_Species<-QCEvents %>% 
  filter(!RareSpecies %in% c(0,1)) %>% 
  select(Unit_Code, Plot_Name, Event_Year, RareSpecies)

#2.18.0
Events_No_Plot_Maint<-QCEvents %>% 
  filter(!PlotMaintReqd %in% c(0,1)) %>% 
  select(Unit_Code, Plot_Name, Event_Year, PlotMaintReqd)

#2.19.0
Events_Not_Verified<-QCEvents %>% 
  filter(!Verified) %>% 
  select(Unit_Code, Plot_Name, Event_Year, Verified, Verified_Date)

#2.20.0
Events_Bad_Verified_Date<-QCEvents %>% 
  filter(Verified_Date!="" & is.na(as.Date(mdy_hms(Verified_Date)))) %>% 
  select(Unit_Code, Plot_Name, Event_Year, Verified, Verified_Date)

Events_Verified_Mismatch<-QCEvents %>% 
  filter((Verified==0  & Verified_Date !="") | (Verified ==1 & is.na(as.Date(mdy_hms(Verified_Date))))) %>% 
  select(Unit_Code, Plot_Name, Event_Year, Verified, Verified_Date)

Events_Verified_Anachronism<-QCEvents %>% 
  filter(Verified_Date!="", as.Date(mdy_hms(Verified_Date))<Event_Date) %>% 
   select(Unit_Code, Plot_Name, Event_Year, Verified, Event_Date, Verified_Date)

#2.21.0

Events_Not_Certified<-QCEvents %>% 
  filter(!Certified) %>% 
  select(Unit_Code, Plot_Name, Event_Year, Certified, Certified_Date)

Events_Certified_Not_Verified<-QCEvents %>% 
  filter(Certified & !Verified) %>% 
  select(Unit_Code, Plot_Name, Event_Year,Verified, Verified_Date, Certified, Certified_Date)

#2.22.0
 Events_Bad_Certified_Date<-QCEvents %>% 
   filter(Certified_Date!="" & is.na(as.Date(mdy_hms(Certified_Date)))) %>% 
   select(Unit_Code, Plot_Name, Event_Year, Certified, Certified_Date)
 
 Events_Certified_Mismatch<-QCEvents %>% 
  filter((Certified==0  & Certified_Date !="") | (Certified ==1 & is.na(as.Date(mdy_hms(Certified_Date))))) %>% 
  select(Unit_Code, Plot_Name, Event_Year, Certified, Certified_Date)
 
 Events_Certified_Anachronism<-QCEvents %>% 
  filter(Certified_Date!="", as.Date(mdy_hms(Certified_Date))<as.Date(mdy_hms(Verified_Date))) %>% 
   select(Unit_Code, Plot_Name, Event_Year, Verified,Certified, Verified_Date, Certified_Date)
 
#2.23.0
 
Events_Bad_Data_Processing<-QCEvents %>% 
  filter(!(DataProcessingLevelID==3 & DataProcessingLevelCode=="A" & DataProcessingLevel=="Accepted" & 
             DataProcessingLevelDefn=="Data that have undergone all QA and QC procedures as defined in a published protocol and associated SOPs. Used in cases where a Quality Assurance Plan (QAP) has not been developed and approved.")  &
           !(DataProcessingLevelID==1 & DataProcessingLevelCode=="R" & DataProcessingLevel=="Raw" & 
             DataProcessingLevelDefn=="Data in their state of original collection, either in the form of paper or electronic field forms, electronic sensor files, or digital media (photo, video, or audio). These data generally have been collected following some QA procedures, but have not undergone any QC procedures.")
           ) %>% 
  select(Unit_Code,Plot_Name,Event_Year, DataProcessingLevelID, DataProcessingLevelCode, DataProcessingLevel, DataProcessingLevelDefn)

#2.24.0 
Events_Data_Processing_Anachronism<-QCEvents %>% 
  filter(DataProcessingLevelDate!="", as.Date(mdy_hms(DataProcessingLevelDate))<+as.Date(mdy_hms(Certified_Date))) %>% 
   select(Unit_Code, Plot_Name, Event_Year, Certified, DataProcessingLevel, Certified_Date, DataProcessingLevelDate)

```

#### **Events Checked:** `r TotEvents` ####

###  Protocol Version
```{r Protocol, echo=FALSE, hold=FALSE, results="asis"}
cat("<br>**Missing Protocol Version**<br>") 
if(nrow(Events_No_Protocol)==0) cat("All events have a protocol version.<br>") else {
   errorText("Events with no protocol version:"); NiceTable(Events_No_Protocol)}

cat("<br>**Wrong Protocol Version**<br>")
if(nrow(Events_Bad_Protocol)==0) cat("All events have the correct protocol version.<br>") else {
   errorText("Events with the wrong protocol version:"); NiceTable(Events_Bad_Protocol)}

```

---

### Event Date

```{r Event_date, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Missing or Incorrect Event Date**<br>")
if(nrow(Events_No_Date)==0) cat("All events have an event date that is after the plot intstallation date.<br>") else {
errorText("Events with no date or that took place before the plot was installed:"); NiceTable(Events_No_Date)}

cat("<br>**Early or Late Events**<br>")
if(nrow(Events_Bad_Date)==0) cat("All events took place between Apr-15 and Sept-30.<br>") else {
errorText("Events not between Apr-15 and Sept-30:"); NiceTable(Events_Bad_Date)}

cat("<br>**Event Year that does not match Event Date**<br>")
if(nrow(Events_Bad_Year)==0) cat("All event years match the event dates.<br>") else {
errorText("There is a mismach between event year and event date:"); NiceTable(Events_Bad_Year)}

```

---

### Event Unit Codes

```{r Event_location, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Missing or Incorrect Event Unit Code**<br>")
if(nrow(Events_Bad_Unit)==0) cat("All events have a recoginized unit code.<br>") else {
errorText("Events without a recognized unit code:"); NiceTable(Events_Bad_Unit)}

cat("<br>**Missing or Incorrect Event Unit Group**<br>")
if(nrow(Events_Bad_Unit_Group)==0) cat("All events have a recognized Unit Group.<br>") else {
errortext("Events with a missing or unrecongized Unit Group:"); NiceTable(Events_Bad_Unit_Group)}

if(nrow(Events_Mismatch_Unit_Group)==0) cat("All events have Unit Group that is consistent with their Unit Code.<br>") else {
errortext("Events with a Unit Group that is inconsistent with their Unit Code:");NiceTable(Events_Mismatch_Unit_Group)}

```

---

### Event Plots

```{r Event-Plots,echo=FALSE, hold=FALSE, results="asis"}
cat("<br>**Missing or Incorrect Plot Name**<br>")
if(nrow(Events_Missing_Plot)==0) cat("All events have a plot name that we use.<br>") else {
errorText("Events without a plot, or from a plot we don't monitor:"); NiceTable(Events_Missing_Plot)}

```

---

### Duplicated Events

```{r Event-Duped,echo=FALSE, hold=FALSE, results="asis"}
cat("<br>**Duplicated Event Data**<br>")
if(nrow(Events_Duplicated)==0) cat("Each plot /date combination is unqiued.<br>") else {
errorText("Plots with more than one event on the same day:"); NiceTable(Events_Duplicated)}

```

---

### Event Panel, Frame and Cycle

```{r Event_Panel_Frame_Cycle,echo=FALSE, hold=FALSE, results="asis"}
cat("<br>**Event Panel Data**<br>")
if(nrow(Events_Bad_Panel)==0) cat("Each event has a panel code from 1 to 4.<br>") else {
errorText("Events without a panel code from 1-4:"); NiceTable(Events_Bad_Panel)}

cat("<br>**Event Frame Data**<br>")
if(nrow(Events_Bad_Frame)==0) cat("Each event has a frame that is either Region or Park.<br>") else {
errorText("Events without a frame of either Region or Park:"); NiceTable(Events_Bad_Frame)}

cat("<br>**Event Cycle Data**<br>")
if(nrow(Events_Bad_Cycle)==0) cat("Each event is from a cycle that matches its event year <br>") else {
errorText("Events without a cycle or with a cycle that does not match its event year:"); NiceTable(Events_Bad_Cycle)}

```

---

### Completed Event Data

```{r Event_Data,echo=FALSE, hold=FALSE, results="asis"}
cat("<br>**Missing Pictures**<br>")
if(nrow(Events_No_Pictures)==0) cat("Every event has pictures taken.<br>") else {
errorText("Events with no pictures taken:"); NiceTable(Events_No_Pictures)}

cat("<br>**Missing CWD**<br>")
if(nrow(Events_No_CWD)==0) cat("Every event has CWD checkboxes checked.<br>") else {
errorText("Events with unchecked CWD checkboxes:"); NiceTable(Events_No_CWD)}

cat("<br>**Invasive Early Detection**<br>")
if(nrow(Events_No_Invasive_Early_Detect)==0) cat("Every event has an appropriate invasive early detection code.<br>") else {
errorText("Events without an appropriate invasive early detection code:"); NiceTable(Events_No_Invasive_Early_Detect)}

cat("<br>**Rare Species Detection**<br>")
if(nrow(Events_No_Rare_Species)==0) cat("Every event has an appropriate rare species detection code.<br>") else {
errorText("Events without an appropriate rare species detection code:"); NiceTable(Events_No_Rare_Species)}

cat("<br>**Plot Maintenance**<br>")
if(nrow(Events_No_Plot_Maint)==0) cat("Every event has an appropriate plot maintenance code.<br>") else {
errorText("Events without an appropriate plot maintenance code:"); NiceTable(Events_No_Plot_Maint)}

```

---

### Data Processing Level

```{r Event_Data_Processing,echo=FALSE, hold=FALSE, results="asis"}
cat("<br>**Data Verfication**<br>")
if(nrow(Events_Not_Verified)==0) cat("All events are verified.<br>") else {
errorText("Events that are not verified:"); NiceTable(Events_Not_Verified)}

if(nrow(Events_Bad_Verified_Date)==0) cat("Verified Date is either a date or blank.<br>") else {
errorText("Events whose verification date is neither a date nor blank"); NiceTable(Events_Bad_Verified_Date)}

if(nrow(Events_Verified_Mismatch)==0) cat("All verified events have a verified date, and no unverified events have a verified date.<br>") else {
errorText("Events whose verificaiton code and verification date are inconsistent:"); NiceTable(Events_Verified_Mismatch)}

if(nrow(Events_Verified_Anachronism)==0) cat("All verified dates are after the event date.<br>") else {
errorText("Events whose verification date is not after the event date:"); NiceTable(Events_Verified_Anachronism)}

cat("<br>**Data Certification**<br>")
if(nrow(Events_Not_Certified)==0) cat("All events are certified.<br>") else {
errorText("Events that are not certified:"); NiceTable(Events_Not_Certified)}

if(nrow(Events_Certified_Not_Verified)==0) cat("Every certified event has been verified.<br>") else {
errorText("Events that are certified but not verified:"); NiceTable(Events_Certified_Not_Verified)}

if(nrow(Events_Bad_Certified_Date)==0) cat("Certified Date is either a date or blank.<br>") else {
errorText("Events whose certification date is neither a date nor blank"); NiceTable(Events_Bad_Certified_Date)}

if(nrow(Events_Certified_Mismatch)==0) cat("All certified events have a certified date, and no uncertified events have a certified date.<br>") else {
errorText("Events whose certification code and certification date are inconsistent:"); NiceTable(Events_Certified_Mismatch)}

if(nrow(Events_Certified_Anachronism)==0) cat("All certified dates are after the verification date.<br>") else {
errorText("Events whose certification date is not after the verification date:"); NiceTable(Events_Certified_Anachronism)}

cat("<br>**Data Processing**<br>")
if(nrow(Events_Bad_Data_Processing)==0) cat("All events have data processing levels are recognized and  consistent.<br>") else {
errorText("Events that have unused or inconsistent data processing levels:"); NiceTable(Events_Bad_Data_Processing)}

if(nrow(Events_Data_Processing_Anachronism)==0) cat("All data processing dates are on or after the certification date.<br>") else {
errorText("Events whose data processing date date is before the certification date:"); NiceTable(Events_Data_Processing_Anachronism)}

```


