---
title: "Forest Vegetation Tree QC"
author: "John Paul Schmit"
date: "5/19/2020"
output: html_document
---


```{r shrub_setup, include=F}
TotShrubs<-nrow(QCShrubs) #Total Number of tree records checked

## Units

# 8.1.0
Shrubs_Bad_Unit<-QCShrubs %>% 
 filter(!Unit_Code %in% c("ANTI", "CATO", "CHOH", "GWMP", "HAFE", "MANA", "MONO", "NACE", "PRWI", "ROCR", "WOTR")) %>% 
 select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name)
  
Shrubs_Bad_Unit_Group<-QCShrubs %>% 
 filter(!Unit_Group %in% c("ANTI","BOHE", "BRUN", "CATO", "CUMB", "GREE", "LOHE", "MAHE", "MANA", "MONO", "NACE", "PISC", "POGO","PRWI", "ROCR", 
                        "SHHI","SHIS","TIDE", "WILL", "WOTR")) %>% 
 select(Unit_Code, Unit_Group, Plot_Name,Sample_Year, Tag, Latin_Name)
  
Shrubs_Mismatch_Unit_Group<-QCShrubs %>% 
   filter(Unit_Code=="ANTI" & Unit_Group!="ANTI"|
          Unit_Code=="CATO" & Unit_Group !="CATO"|
          Unit_Code=="CHOH" & !Unit_Group %in% c("BRUN", "CUMB", "POGO", "WILL") |
          Unit_Code =="GWMP" & !Unit_Group %in% c("POGO","TIDE") |
          Unit_Code =="HAFE" & !Unit_Group %in% c("BOHE", "LOHE", "MAHE","SHHI", "SHIS")|
          Unit_Code=="MANA" & Unit_Group !="MANA" |
          Unit_Code=="MONO" & Unit_Group !="MONO" |
          Unit_Code=="NACE" & !Unit_Group %in% c("GREE","NACE","PISC")|
          Unit_Code=="PRWI" & Unit_Group !="PRWI" |
          Unit_Code=="ROCR" & Unit_Group !="ROCR" |
          Unit_Code=="WOTR" & Unit_Group!="WOTR"
          ) %>% 
     select(Plot_Name, Unit_Code, Unit_Group, Sample_Year, Tag, Latin_Name)

## Plots

#8.2.0
 Shrubs_No_Plot_Name<-QCShrubs %>% 
    filter(is.na(Plot_Name) | Plot_Name=="") %>% 
    select(Unit_Code, Plot_Name,Sample_Year, Tag, Latin_Name)
  
## Panel Frame Cycle  
 
#8.3.0
Shrubs_Bad_Panel<-QCShrubs %>%
 filter(!Panel %in% 1:4) %>% 
 select(Unit_Code, Plot_Name, Sample_Year, Panel,Tag, Latin_Name)
 
#8.4.0
Shrubs_Bad_Frame<-QCShrubs %>%
  filter(!Frame %in% c("Park","Region")) %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Frame,Tag, Latin_Name)
  
#8.5.0
Shrubs_Bad_Cycle<-QCShrubs %>% 
  filter(!(Cycle==1 & Sample_Year %in% 2005:2009) &
         !(Cycle==2 & Sample_Year %in% 2010:2013) &
         !(Cycle==3 & Sample_Year %in% 2014:2017) &
         !(Cycle==4 & Sample_Year %in% 2018:2022)) %>% 
  select(Unit_Code,Plot_Name, Sample_Year, Cycle,Tag, Latin_Name)
 
## Dates

#8.6.0
Shrubs_Bad_Date<-QCShrubs %>% 
  filter(!ymd(Date) %in% QCEvents$Event_Date) %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Date, Tag, Latin_Name)
 
#8.7.0
Shrubs_Bad_Year<-QCShrubs %>% 
 filter(Sample_Year != year(ymd(Date))) %>% 
 select(Unit_Code, Plot_Name, Sample_Year,Date, Tag, Latin_Name)

## Shrub Tag
 
#8.8.0
Shrubs_Bad_Tag<-QCShrubs %>% filter(!Tag %in%1:30000) %>%
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name)

Shrubs_Duplicate_Tag<-QCShrubs%>% group_by(Cycle,Tag) %>% 
  summarize(Count=n()) %>% filter(Count!=1)

## Microplot

#6.9.0
Shrubs_Bad_Microplot<-QCShrubs %>% filter(!Microplot_Number %in% c(60,180,300)) %>% 
 select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Microplot_Number)

## Latin Name

# 8.10.0
Shrubs_No_Name<-QCShrubs %>% filter(Latin_Name=="") %>%
 select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name)

Shrubs_Many_Names<-QCShrubs %>% group_by(Tag) %>% 
  filter(n_distinct(Latin_Name)!=1)  %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name)

Shrubs_Anachronistic_Name <-QCShrubs %>% filter(
   (Sample_Year < 2008 & Latin_Name == "Alnus serrulata") | (Sample_Year < 2008 & Latin_Name == "Castanea pumila") |
   (Sample_Year < 2016 & Latin_Name == "Cephalanthus occidentalis") | (Sample_Year < 2008 & Latin_Name == "Cornus amomum") |
   (Sample_Year < 2007 & Latin_Name == "Euonymus americanus") | (Sample_Year < 2007 & Latin_Name == "Euonumus atropurpureus") |
   (Sample_Year < 2008 & Latin_Name == "Ligustrum ovalifolium") | (Sample_Year < 2014 & Latin_Name == "Ligustrum sinense") |
   (Sample_Year < 2008 & Latin_Name == "Ligustrum vulgare") | (Sample_Year < 2008 & Latin_Name == "Lonicera morrowii") |
   (Sample_Year < 2014 & Latin_Name == "Mahonia bealei") |  (Sample_Year < 2014 & Latin_Name == "Quercus ilicifolia") |
   (Sample_Year < 2007 & Latin_Name == "Rhododendron periclymenoides") | (Sample_Year < 2014 & Latin_Name == "Rhodotypos scandens") |
   (Sample_Year < 2008 & Latin_Name == "Rhus copallina") | (Sample_Year < 2008 & Latin_Name == "Sambucus canadensis") |
   (Sample_Year < 2007 & Latin_Name == "Sambucus pubens") | (Sample_Year < 2014 & Latin_Name == "Spiraea japonica") |
   (Sample_Year < 2013 & Latin_Name == "Vaccinium stamineum") | (Sample_Year < 2013 & Latin_Name == "Viburnum dilatatum") |
   (Sample_Year < 2007 & Latin_Name == "Viburnum plicatum") | (Sample_Year < 2007 & Latin_Name == "Viburnum prunifolium") |
   (Sample_Year < 2014 & Latin_Name == "Viburnum recognitum") | (Sample_Year < 2007 & Latin_Name == "Viburnum sieboldii") |
   (Sample_Year > 2009 & Latin_Name == "Gaylussacia frondosa") | (Sample_Year > 2009 & Latin_Name == "Rosa carolina") |
   (Sample_Year > 2009 & Latin_Name == "Rubus argutus") | (Sample_Year > 2009 & Latin_Name == "Symphoricarpos orbiculatus") |
   (Sample_Year < 2014 & Latin_Name == "Viburnum acerifolium") | (Sample_Year > 2014 & Latin_Name == "Ilex verticillata") |
   (Sample_Year > 2014 & Latin_Name == "Lindera benzoin") | (Sample_Year > 2014 & Latin_Name == "Kalmia latifolia")
 ) %>% 
   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status)
 

# ## TSN

# 8.11.0
Shrubs_No_TSN<-QCShrubs %>% filter(is.na(TSN) | TSN=="") %>%
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, TSN)

Shrubs_Many_TSN<-QCShrubs %>% group_by(Tag) %>% 
 filter(n_distinct(TSN)!=1)  %>% 
 select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, TSN)

## Status
 
#8.12..0
Shrubs_Bad_Status<-QCShrubs %>% filter(!Status %in% c(Live_Status, Dead_Status, Missing_Status, Other_Status) ) %>%
   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status)
  
## Habit

#8.13.0
Shrubs_Bad_Habit<-QCShrubs %>% filter(!Habit=="Shrub") %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Habit) 

## Vigor

#8.14.0
 
Shrubs_Live_Bad_Vigor<-QCShrubs %>% filter(Status %in% Live_Status & 
         ( (Sample_Year<2017 & !is.na(SaplingVigor)) | (Sample_Year >=2017 & is.na(SaplingVigor))  | 
            (Sample_Year >=2017 & !SaplingVigor %in% 0:5))) %>% 
   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, SaplingVigor)
  
Shrubs_Unalive_Bad_Vigor<-QCShrubs %>% filter(!Status %in% Live_Status, !is.na(SaplingVigor)) %>% 
    select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, SaplingVigor)

#8.15.0
 
Shrubs_Bad_Vigor_Class<-QCShrubs %>% filter( (SaplingVigor==0 & !is.na(VigorClass)) |
                                             (SaplingVigor==1 & VigorClass != "Healthy") |
                                             (SaplingVigor==2 & VigorClass !="Light Decline") |
                                             (SaplingVigor==3 & VigorClass !="Moderate Decline") |
                                             (SaplingVigor==4 & VigorClass !="Severe Decline") |
                                             (SaplingVigor==5 & VigorClass !="Functionally Dead") |
                                             (is.na(SaplingVigor) & VigorClass!="") ) %>% 
      select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, SaplingVigor, VigorClass)


## Shrub Browse

#8.16.0
 Shrubs_Live_Bad_Browsable<-QCShrubs %>% filter(Status %in% Live_Status & !Browsable %in% c("Yes","No", "unk") ) %>% 
   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, Browsable, Browsed)

 Shrubs_Live_Anachronistic_Browsable<-QCShrubs %>% filter(Status %in% Live_Status & Sample_Year<2010 & Browsable != "unk" ) %>% 
   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, Browsable, Browsed)
 
 Shrubs_Unalive_Browsable<-QCShrubs %>% filter(!Status %in% Live_Status & Browsable !="" ) %>% 
   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, Browsable, Browsed)

#8.17.0  
 Shrubs_Live_Bad_Browsed<-QCShrubs %>% filter(Status %in% Live_Status & !Browsed %in% c("Yes","No") ) %>% 
   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, Browsable, Browsed)
 
 Shrubs_Unalive_Browsed<-QCShrubs %>% filter(!Status %in% Live_Status & Browsed !="" ) %>% 
   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, Browsable, Browsed)
 
#8.18.0
 Shrubs_Live_Illogical_Browse <- QCShrubs %>% filter(Status %in% Live_Status, Browsed =="Yes", Browsable == "No") %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, Browsable, Browsed)
 
 
### Multi-Year Checks

Repeat_Shrubs<-QCAllShrubs %>% group_by(Tag) %>% summarize(Records=n()) %>% filter(Records>1) %>% pull(Tag)

##Status  Change 

#8.19.0
 Shrubs_Start_Wrong<-if(length(Repeat_Shrubs>0)){
   QCAllShrubs %>% filter(Tag %in% Repeat_Shrubs) %>%
   group_by(Tag) %>% arrange(Tag, Sample_Year) %>%
   filter(any(Sample_Year==min(Sample_Year) & (Status  %in% c(Missing_Status, Other_Status, Dead_Status)) |
          (Status %in% Dead_Status & Sample_Year < 2010 )) ) %>%
   mutate(Start_Year=min(Sample_Year)) %>% arrange(Sample_Year) %>%
   select(Plot_Name, Cycle, Tag, Latin_Name, Status, Start_Year) %>%
     pivot_wider(id_cols=c(Plot_Name, Tag, Latin_Name, Start_Year) , names_from = Cycle,
               names_prefix = "Cycle ", values_from = Status)} else data.frame()
 
# 8.20.0
 Shrubs_Dead_Plus<-if(length(Repeat_Shrubs>0)){
    QCAllShrubs %>% filter(Tag %in% Repeat_Shrubs) %>%  
    group_by(Tag) %>% arrange(Tag, Sample_Year) %>%
    filter(any(Sample_Year!=max(Sample_Year) & Status %in% Dead_Status)) %>%
    mutate(Start_Year=min(Sample_Year)) %>% arrange(Sample_Year) %>%
    select(Plot_Name, Cycle, Sample_Year, Tag, Latin_Name, Status, Start_Year) %>%
    pivot_wider(id_cols = c(Plot_Name, Tag, Latin_Name, Start_Year), names_prefix = "Cycle ",
               values_from = Status, names_from = Cycle )
    } else data.frame()

 
#8.21.0
Shrubs_Levitated<-if(length(Repeat_Shrubs>0)){
  QCAllShrubs %>% filter(Tag %in% Repeat_Shrubs) %>%
  group_by(Tag) %>% arrange(Tag, Sample_Year) %>%
  filter(any(Status =="Alive Fallen" & lead(Status, order_by=Sample_Year) %in% c("Alive Broken",
           "Alive Standing","Dead Standing"))) %>%
  mutate(Start_Year=min(Sample_Year)) %>% arrange(Sample_Year) %>%
   select(Plot_Name, Cycle, Sample_Year, Tag, Latin_Name, Status, Start_Year) %>%
   pivot_wider(id_cols = c(Plot_Name, Tag, Latin_Name, Start_Year), names_prefix = "Cycle ",
               values_from = Status, names_from = Cycle ) } else data.frame()

#8.22.0
Shrubs_Found_Alive<-if(length(Repeat_Shrubs>0)){
  QCAllShrubs %>% filter(Tag %in% Repeat_Shrubs) %>%
  group_by(Tag) %>% arrange(Tag, Sample_Year) %>%
  filter(any( (Status %in% Missing_Status) & (lead(Status, order_by=Sample_Year) %in% Live_Status) )) %>%
  mutate(Start_Year=min(Sample_Year)) %>% arrange(Sample_Year) %>%
   select(Plot_Name, Cycle, Sample_Year, Tag, Latin_Name, Status, Start_Year) %>%
   pivot_wider(id_cols = c(Plot_Name, Tag, Latin_Name, Start_Year), names_prefix = "Cycle ",
               values_from = Status, names_from = Cycle ) } else data.frame()

#8.23.0
Shrubs_Downgraded_Persisting <-if(length(Repeat_Shrubs>0)){
  QCAllShrubs %>% filter(Tag %in% Repeat_Shrubs) %>%
  group_by(Tag) %>% arrange(Tag, Sample_Year) %>%
  filter(any( (Status =="Downgraded to Non-Sampled") & (lead(Status, order_by=Sample_Year) %in%
                           c(Live_Status, Dead_Status, Other_Status, Missing_Status)) )) %>%
  mutate(Start_Year=min(Sample_Year)) %>% arrange(Sample_Year) %>%
   select(Plot_Name, Cycle, Sample_Year, Tag, Latin_Name, Status, Start_Year) %>%
   pivot_wider(id_cols = c(Plot_Name, Tag, Latin_Name, Start_Year), names_prefix = "Cycle ",
               values_from = Status, names_from = Cycle ) } else data.frame()

#8.24.0
 Shrubs_Triple_Missing <-if(length(Repeat_Shrubs>0)){
   QCAllShrubs %>% filter(Tag %in% Repeat_Shrubs) %>%
   group_by(Tag) %>% arrange(Tag, Sample_Year) %>%
   mutate(Start_Year=min(Sample_Year)) %>%
   filter(any( (Status %in% Missing_Status) & (lead(Status, order_by=Sample_Year) %in% Missing_Status)
               & (lead(Status,n=2, order_by=Sample_Year) %in% Missing_Status))) %>%
    arrange(Sample_Year) %>%
    select(Plot_Name, Cycle, Sample_Year, Tag, Latin_Name, Status, Start_Year) %>%
    pivot_wider(id_cols = c(Plot_Name, Tag, Latin_Name, Start_Year), names_prefix = "Cycle ",
                values_from = Status, names_from = Cycle ) } else data.frame()

## Vigor Change

#8.25.0
 Shrubs_Vigor_Jump <-if(length(Repeat_Shrubs>0)){
   QCAllShrubs %>% filter(Tag %in% Repeat_Shrubs) %>%
   group_by(Tag) %>% arrange(Tag, Sample_Year) %>%
  mutate(Start_Year=min(Sample_Year)) %>%
   filter(any(
     (VigorClass =="Moderate Decline" & lead(Status, order_by=Sample_Year) == "Healthy") |
     (VigorClass =="Functionally Dead" & lead(Status, order_by=Sample_Year) %in% c("Healthy", "Light Decline"))
     )) %>%
    arrange(Sample_Year) %>%
    select(Plot_Name, Cycle, Sample_Year, Tag, Latin_Name, VigorClass, Start_Year) %>%
    pivot_wider(id_cols = c(Plot_Name, Tag, Latin_Name, Start_Year), names_prefix = "Cycle ",
                values_from = VigorClass, names_from = Cycle ) } else data.frame()


```


#### **Shrubs Checked:** `r TotShrubs` ####


### Unit Codes

```{r Shrub_Unit_Codes, echo=FALSE, hold=FALSE, results="asis"}
if(nrow(Shrubs_Bad_Unit)==0) cat("All shrubs have a recognized Unit Code.<br>") else {
   cat(errortext("Shrubs with a missing or unrecongized Unit Code:")); NiceTable(Shrubs_Bad_Unit)}
  
if(nrow(Shrubs_Bad_Unit_Group)==0) cat("All shrubs have a recognized Unit Group.<br>") else {
 cat( errortext("Shrubs with a missing or unrecongized Unit Group:")); NiceTable(Shrubs_Bad_Unit_Group)}
 
if(nrow(Shrubs_Mismatch_Unit_Group)==0) cat("All shrubs have a Unit Group that is consistent with their Unit Code.<br>") else {
    cat(errortext("Shrubs with a Unit Group that is inconsistent with their Unit Code:")); NiceTable(Shrubs_Mismatch_Unit_Group)}

```

---

### Plot Names

```{r Shrub_plot_names, echo=FALSE, hold=FALSE, results="asis"}
if(nrow(Shrubs_No_Plot_Name)==0) cat("All shrubs have a Plot Name.<br>") else {
 errortext("Shrubs with a missing Plot Name:"); NiceTable(Shrubs_No_Plot_Name)}
```

---

### Event Panel, Frame and Cycle

```{r Shrub_Panel_Frame_Cycle,echo=FALSE, hold=FALSE, results="asis"}
 
cat("<br>**Shrub Panel Data**<br>")
if(nrow(Shrubs_Bad_Panel)==0) cat("Each shrub has a panel code from 1 to 4.<br>") else {
errorText("Shrubs without a panel code from 1-4:"); NiceTable(Shrubs_Bad_Panel)}

cat("<br>**Shrub Frame Data**<br>")
if(nrow(Shrubs_Bad_Frame)==0) cat("Each shrub has a frame that is either Region or Park.<br>") else {
errorText("Shrubs without a frame of either Region or Park:"); NiceTable(Shrubs_Bad_Frame)}

cat("<br>**Shrub Cycle Data**<br>")
if(nrow(Shrubs_Bad_Cycle)==0) cat("Each shrub is from a cycle that matches its event year <br>") else {
errorText("Shrubs without a cycle or with a cycle that does not match its event year:"); NiceTable(Shrubs_Bad_Cycle)}

```

---

###  Dates
```{r Shrub_Dates, echo=FALSE, hold=FALSE, results="asis"}

if(nrow(Shrubs_Bad_Date)==0) cat("All shrub dates match an event date.<br>") else {
 errorText("Shrubs whose date does not match an event date:"); NiceTable(Shrubs_Bad_Date)}

if(nrow(Shrubs_Bad_Year)==0) cat("All shrub dates and sample years are consistent.<br>") else {
 errorText("Shrubs whose date does not match its sample year:"); NiceTable(Shrubs_Bad_Year)}

```

---

### Tag

```{r Shrub_Tag, echo=FALSE, hold=FALSE, results="asis"}
 
if(nrow(Shrubs_Bad_Tag)==0) cat("All shrub records have a valid tag.<br>") else {
    errorText("Shrub records with no tag or a tag <1 or >30,000 tag:"); NiceTable(Shrubs_Bad_Tag)}

if(nrow(Shrubs_Duplicate_Tag)==0) cat("No tags are duplicated in a single visit.<br>") else {
  errorText("Shrubs with duplicate tag records:"); NiceTable(Shrubs_Duplicate_Tag)}

```

---

### Microplot

```{r Shrub_Microplot, echo=FALSE, hold=FALSE, results="asis"}
if(nrow(Shrubs_Bad_Microplot)==0) cat("All shrubs have a microplot of 60, 180 or 300.<br>") else {
   errorText("Shrubs with a microplot number that is not 60, 180 or 300:"); NiceTable(Shrubs_Bad_Microplot)}
```

---

### Species ID

```{r Shrub_Species, echo=FALSE, hold=FALSE, results="asis"}
 
if(nrow(Shrubs_No_Name)==0) cat("All shrub records checked have a species ID.<br>") else {
 errorText("Shrubs with no species name:"); NiceTable(Shrubs_No_Name)}

if(nrow(Shrubs_Many_Names)==0) cat("All shrubs have only one species ID.<br>") else {
 errorText("Shrubs with multiple species names:"); NiceTable(Shrubs_Many_Names)}

if(nrow(Shrubs_Anachronistic_Name)==0) cat("All shrub species were only monitored once they were part of protocol.<br>") else {
 errorText("Shrubs monitored before they were part of protocol:"); NiceTable(Shrubs_Anachronistic_Name)}

if(nrow(Shrubs_No_TSN)==0) cat("All shrub records checked have a TSN.<br>") else {
 errorText("Shrubs with no TSN:"); NiceTable(Shrubs_No_TSN)}

if(nrow(Shrubs_Many_TSN)==0) cat("All shrubs have only one TSN.<br>") else {
 errorText("Shrubs with multiple TSB:"); NiceTable(Shrubs_Many_TSN)}

```

---

###  Status
```{r Shrub_Status, echo=FALSE, hold=FALSE, results="asis"}

if(nrow(Shrubs_Bad_Status)==0) cat("All shrub records have a valid status.<br>") else {
  errorText("Shrub records without a status or a status we do not use:"); NiceTable(Shrubs_Bad_Status)}

```

---

### Habit

```{r Shrub_Habit, echo=FALSE, hold=FALSE, results="asis"}

 if(nrow(Shrubs_Bad_Habit)==0) cat("All shrub records have a habit of 'Shrub'.<br>") else {
    errorText("Shrub records without a habit of 'Shrub':"); NiceTable(Shrubs_Bad_Habit)}

```

---

### Vigor

```{r Shrub_vigor, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Living Shrubs Vigor Invalid**<br>") 
  if(nrow(Shrubs_Live_Bad_Vigor)==0) cat("All live shrubs have a valid vigor.<br>") else {
   errorText("Living shrub records with a vigor other than 0-5:"); NiceTable(Shrubs_Live_Bad_Vigor)}
 
cat("<br>**Non-Living Shrubs with Vigor**<br>")
  if(nrow(Shrubs_Unalive_Bad_Vigor)==0) cat("No non-living shrubs have a vigor.<br>") else {
     errorText("Non-living shrub records with a vigor:"); NiceTable(Shrubs_Unalive_Bad_Vigor)}

cat("<br>**Shrubs with Inconsistent Vigor and Vigor Class**<br>")
if(nrow(Shrubs_Bad_Vigor_Class)==0) cat("All shrubs have consisntent vigor and vigor classes.<br>") else {
 errorText("Shrubs with inconsistent vigor and vigor classes:"); NiceTable(Shrubs_Bad_Vigor_Class)}

```


---

### Shrub Browse

```{r Shrub_Browse, echo=FALSE, hold=FALSE, results="asis"}
  
 cat("<br>**Living Shrubs Browsable Status Invalid**<br>") 
   if(nrow(Shrubs_Live_Bad_Browsable)==0) cat("All live shrubs have a valid browsable status.<br>") else {
      errorText("Living shrub records with a browsable status other than Yes, No, or unk:"); NiceTable(Shrubs_Live_Bad_Browsable)}
 
 cat("<br>**Living Shrubs Anachronistic Browsable Status**<br>") 
   if(nrow(Shrubs_Live_Anachronistic_Browsable)==0) cat("No living shrubs records have a browsable status before 2010.<br>") else {
      errorText("Living shrubs records with a browsable status before 2010:"); NiceTable(Shrubs_Live_Anachronistic_Browsable)}
 
  cat("<br>**Non-Living Shrubs with Browsable Status**<br>")
    if(nrow(Shrubs_Unalive_Browsable)==0) cat("No non-living shrubs have a browsable status.<br>") else {
       errorText("Non-living shrub records with a browsable status:"); NiceTable(Shrubs_Unalive_Browsable)}
 
  cat("<br>**Living Shrubs Browsed Status Invalid**<br>") 
   if(nrow(Shrubs_Live_Bad_Browsed)==0) cat("All live shrubs have a valid browsed status.<br>") else {
      errorText("Living shrub records with a browsed status other than Yes, or No:"); NiceTable(Shrubs_Live_Bad_Browsed)}
 
  cat("<br>**Non-Living Shrubs with Browsed Status**<br>")
    if(nrow(Shrubs_Unalive_Browsed)==0) cat("No non-living shrubs have a browsed status.<br>") else {
       errorText("Non-living shrub records with a browsed status:"); NiceTable(Shrubs_Unalive_Browsed)}
 
   cat("<br>**Living Shrubs with Illogical Browsing**<br>")
    if(nrow(Shrubs_Live_Illogical_Browse)==0) cat("No living shrubs have contradictory browsable and browsed status.<br>") else {
       errorText("Living shrub records with a browsable status of 'No' and browsed status of'Yes':"); NiceTable(Shrubs_Live_Illogical_Browse)}
 
```

---

### **Change Over Time**

### Shrub Status Discrepancies

```{r Shrub_Status_Change, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Shrubs that Start in a Non-Sampled Status**<br>")
  if(nrow(Shrubs_Start_Wrong)==0) cat("No shrubs start as missing downgraded, or dead fallen.<br>") else {
    errorText("Shrubs that start in a non-sampled status:"); NiceTable(Shrubs_Start_Wrong)}

cat("<br>**Shrubs that are Sampled after they are Dead**<br>")
  if(nrow(Shrubs_Dead_Plus)==0) cat("No shrub was sampled after it was dead.<br>") else {
    errorText("Shrubs that were reorded as dead and then sampled again:"); NiceTable(Shrubs_Dead_Plus)}
 
cat("<br>**Shrubs that Fell Down and then Levitated Back Up**<br>")
  if(nrow(Shrubs_Levitated)==0) cat("No shrub was Alive Fallen and then became Standing.<br>") else {
    errorText("Shrubs that were Alive Fallen but then became Standing:"); NiceTable(Shrubs_Levitated)}
 
cat("<br>**Shrubs that went Missing and were Found Alive**<br>")
  if(nrow(Shrubs_Found_Alive)==0) cat("No shrub was Missing and then found Alive.<br>") else {
    errorText("Shrubs that were Missing but then were found Alive:"); NiceTable(Shrubs_Found_Alive)}
 
cat("<br>**Shrubs that were Downgraded and resampled**<br>")
  if(nrow(Shrubs_Downgraded_Persisting)==0) cat("No shrub was resampled after being downgraded.<br>") else {
    errorText("Shrubs that were Downgraded but then were resampled:"); NiceTable(Shrubs_Downgraded_Persisting)}
 
cat("<br>**Shrubs that went Missing Three Times in a Row**<br>")
  if(nrow(Shrubs_Triple_Missing)==0) cat("No shrub went missing 3 consecutive visits.<br>") else {
    errorText("Shrubs that were Missing three times in a row:"); NiceTable(Shrubs_Triple_Missing)}

```

---

### Shrub Vigor Change
```{r Shrub_Vigor_Change, echo=FALSE, hold=FALSE, results="asis"}

 cat("<br>**Shrubs that have a Large Improvement in Vigor**<br>")
 if(nrow(Shrubs_Vigor_Jump)==0) cat("No shrub has a 2 class improvement in vigor.<br>") else {
     errorText("Shrubs that have a 2 class improvement in vigor:"); NiceTable(Shrubs_Vigor_Jump)}
```





