---
title: "Forest Vegetation Foliage Conditions QC"
author: "John Paul Schmit"
date: "5/19/2020"
output: html_document
---


```{r foliage_setup, include=F}


TotFol<-nrow(QCFoliage) #Total number of stem records checked

## Units
 
#10.1.0
Foliage_Bad_Unit<-QCFoliage %>% 
   filter(!Unit_Code %in% c("ANTI", "CATO", "CHOH", "GWMP", "HAFE", "MANA", "MONO", "NACE", "PRWI", "ROCR", "WOTR")) %>% 
   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name)

Foliage_Bad_Unit_Group<-QCFoliage %>% 
    filter(!Unit_Group %in% c("ANTI","BOHE", "BRUN", "CATO", "CUMB", "GREE", "LOHE", "MAHE", "MANA", "MONO", "NACE", "PISC", "POGO","PRWI", "ROCR", 
                             "SHHI","SHIS","TIDE", "WILL", "WOTR")) %>% 
    select(Unit_Code, Unit_Group, Plot_Name,Sample_Year, Tag, Latin_Name)
 
Foliage_Mismatch_Unit_Group<-QCFoliage %>% 
    filter(Unit_Code=="ANTI" & Unit_Group!="ANTI"|
              Unit_Code=="CATO" & Unit_Group !="CATO"|
              Unit_Code=="CHOH" & !Unit_Group %in% c("BRUN", "CUMB", "POGO", "WILL") |
              Unit_Code =="GWMP" & !Unit_Group %in% c("POGO","TIDE") |
              Unit_Code =="HAFE" & !Unit_Group %in% c("BOHE", "LOHE", "MAHE","SHHI", "SHIS")|
              Unit_Code=="MANA" & Unit_Group !="MANA" |
              Unit_Code=="MONO" & Unit_Group !="MONO" |
              Unit_Code=="NACE" & !Unit_Group %in% c("GREE","NACE","PISC")|
              Unit_Code=="PRWI" & Unit_Group !="PRWI" |
              Unit_Code=="ROCR" & Unit_Group !="ROCR" |
              Unit_Code=="WOTR" & Unit_Group!="WOTR"
           ) %>% 
    select(Plot_Name, Unit_Code, Unit_Group, Sample_Year, Tag, Latin_Name)
  
#10.2.0
Foliage_No_Plot_Name<-QCFoliage %>% 
 filter(is.na(Plot_Name) | Plot_Name=="") %>% 
 select(Unit_Code, Plot_Name,Sample_Year, Tag, Latin_Name)

## Panel Frame Cycle  

#10.3.0
Foliage_Bad_Panel<-QCFoliage %>%
 filter(!Panel %in% 1:4) %>% 
 select(Unit_Code, Plot_Name, Sample_Year, Panel,Tag, Latin_Name)

#10.4.0
Foliage_Bad_Frame<-QCFoliage %>%
 filter(!Frame %in% c("Park","Region")) %>% 
 select(Unit_Code, Plot_Name, Sample_Year, Frame,Tag, Latin_Name)

#10.5.0
Foliage_Bad_Cycle<-QCFoliage %>% 
 filter(!(Cycle==1 & Sample_Year %in% 2005:2009) &
       !(Cycle==2 & Sample_Year %in% 2010:2013) &
       !(Cycle==3 & Sample_Year %in% 2014:2017) &
       !(Cycle==4 & Sample_Year %in% 2018:2022)) %>% 
 select(Unit_Code,Plot_Name, Sample_Year, Cycle,Tag, Latin_Name)
 
## Dates
 
#10.6.0
Foliage_Bad_Date<-QCFoliage %>% 
 filter(!ymd(Date) %in% QCEvents$Event_Date) %>% 
 select(Unit_Code, Plot_Name, Sample_Year, Date, Tag, Latin_Name)
 
#10.7.0
Foliage_Bad_Year<-QCFoliage %>% 
 filter(Sample_Year != year(ymd(Date))) %>% 
 select(Unit_Code, Plot_Name, Sample_Year,Date, Tag, Latin_Name)

# ## Condition Record Tags
#  
# # 9.8.0
# Conditions_Bad_Tag<-QCConditions %>% filter(!Tag %in% 1:30000) %>%
#  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name)
#  
# Conditions_No_Plant<-QCConditions %>% anti_join(
#   bind_rows(QCTrees %>% select(Tag, Sample_Year),
#             QCSaplings %>% select(Tag, Sample_Year),
#             QCShrubs %>% select(Tag, Sample_Year))
#   ) %>% 
#    select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Condition)
# 
# ## Latin Name
# 
# # 9.9.0
# Condtions_No_Name<-QCConditions %>% filter(Latin_Name=="") %>%
#  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name)
# 
# Conditions_Wrong_Name<-QCConditions %>% anti_join(
#   bind_rows(QCTrees %>% select(Tag, Sample_Year, Latin_Name),
#             QCSaplings %>% select(Tag, Sample_Year, Latin_Name),
#             QCShrubs %>% select(Tag, Sample_Year, Latin_Name))
#   ) %>% 
#    select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Condition)
# 
# ## TSN
# 
# # 9.10.0
# Conditions_No_TSN <-QCConditions %>% filter(is.na(TSN) | TSN=="") %>%
#  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, TSN)
# 
# Conditions_Wrong_TSN<-QCConditions %>% anti_join(
#   bind_rows(QCTrees %>% select(Tag, Sample_Year, TSN),
#             QCSaplings %>% select(Tag, Sample_Year, TSN),
#             QCShrubs %>% select(Tag, Sample_Year, TSN))
#   ) %>% 
#    select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, TSN, Condition)

## Foliage

# #5.15.0
# Trees_Bad_Foliage_Condition<-QCFoliage %>% filter(Sample_Year  %in% QCYears & (is.na(Condition_Description) | 
#               !Condition_Description %in% c("Chlorosis","Holes","Necrosis","Small leaves","Wilting","Other") )) %>% 
#   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Condition_Description, Percent_Afflicted)
#   
# #5.16.0
# Trees_Bad_Foliage_Percent<-QCFoliage %>% filter(Sample_Year  %in% QCYears & (is.na(Percent_Afflicted) | 
#                             Percent_Afflicted<1 |Percent_Afflicted>100)) %>% 
#     select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Condition_Description, Percent_Afflicted)
# 
# #5.17.0
# Trees_Redundant_Foliage<-QCFoliage %>% filter(Sample_Year  %in% QCYears) %>% 
#   group_by(Tag, Sample_Year) %>% filter(n()!=n_distinct(Condition_Description)) %>%
#   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Condition_Description, Percent_Afflicted)

#5.18.0
#Trees_Unalive_Foliage<- QCFoliage %>% filter(Sample_Year %in% QCYears & !Status %in% Live_Status ) %>% 
#    select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, Condition_Description, Percent_Afflicted)

## Foliage

#6.16.0
# Saplings_Bad_Foliage_Condition<-QCFoliage %>% filter(Sample_Year  %in% QCYears & (is.na(Condition_Description) | 
#               !Condition_Description %in% c("Chlorosis","Holes","Necrosis","Small leaves","Wilting","Other") )) %>% 
#   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Condition_Description, Percent_Afflicted)
#   
# 
# Trees_Bad_Foliage_Percent<-QCFoliage %>% filter(Sample_Year  %in% QCYears & (is.na(Percent_Afflicted) | 
#                             Percent_Afflicted<1 |Percent_Afflicted>100)) %>% 
#     select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Condition_Description, Percent_Afflicted)
# 
# Trees_Unalive_Foliage<- QCFoliage %>% filter(Sample_Year %in% QCYears & !Status %in% Live_Status ) %>% 
#     select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, Condition_Description, Percent_Afflicted)



```

#### **Foliage Records Checked:** `r TotFol` ####

### Unit Codes

```{r Foliage_Unit_Codes, echo=FALSE, hold=FALSE, results="asis"}
 if(nrow(Foliage_Bad_Unit)==0) cat("All foliage records have a recognized Unit Code.<br>") else {
    errortext("Foliage records with a missing or unrecongized Unit Code:"); NiceTable(Foliage_Bad_Unit)}
 
 if(nrow(Foliage_Bad_Unit_Group)==0) cat("All foliage records have a recognized Unit Group.<br>") else {
    errortext("Foliage records with a missing or unrecongized Unit Group:"); NiceTable(Foliage_Bad_Unit_Group)}
  
 if(nrow(Foliage_Mismatch_Unit_Group)==0) cat("All foliage records have Unit Group that is consistent with their Unit Code.<br>") else {
     errortext("Foliage records with a Unit Group that is inconsistent with their Unit Code:");NiceTable(Foliage_Mismatch_Unit_Group)}

```

---

### Plot Names

```{r Foliage_plot_names, echo=FALSE, hold=FALSE, results="asis"}
if(nrow(Foliage_No_Plot_Name)==0) cat("All foliage records have a Plot Name.<br>") else {
 errortext("Foliage records with a missing Plot Name:"); NiceTable(Foliage_No_Plot_Name)}

```

---

### Event Panel, Frame and Cycle

```{r Foliage_Panel_Frame_Cycle,echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Panel Data**<br>")
if(nrow(Foliage_Bad_Panel)==0) cat("Each foliage record has a panel code from 1 to 4.<br>") else {
errorText("Foliage records without a panel code from 1-4:"); NiceTable(Foliage_Bad_Panel)}
    
cat("<br>**Frame Data**<br>")
if(nrow(Foliage_Bad_Frame)==0) cat("Each foliage record has a frame that is either Region or Park.<br>") else {
errorText("Foliage records without a frame of either Region or Park:"); NiceTable(Foliage_Bad_Frame)}

cat("<br>**Cycle Data**<br>")
if(nrow(Foliage_Bad_Cycle)==0) cat("Each foliage record is from a cycle that matches its event year <br>") else {
errorText("Foliage records without a cycle or with a cycle that does not match its event year:"); NiceTable(Foliage_Bad_Cycle)}

```

---

###  Dates
```{r Foliage_Dates, echo=FALSE, hold=FALSE, results="asis"}

if(nrow(Foliage_Bad_Date)==0) cat("All foliage record dates match an event date.<br>") else {
errorText("Foliage records whose date does not match an event date:"); NiceTable(Foliage_Bad_Date)}

if(nrow(Foliage_Bad_Year)==0) cat("All foliage record dates and sample years are consistent.<br>") else {
errorText("Foliage records whose date does not match its sample year:"); NiceTable(Foliage_Bad_Year)}

```

---

### Tag

```{r Foliage_Tag, echo=FALSE, hold=FALSE, results="asis"}
# if(nrow(Conditions_Bad_Tag)==0) cat("All condition records have a valid tag.<br>") else {
#   errorText("Condition records with no tag or a tag <1 or >30,000 tag:"); NiceTable(Conditions_Bad_Tag)}
#  
# if(nrow(Conditions_No_Plant)==0) cat("All condition records are matched with a tree, sapling or shrub record.<br>") else {
#     errorText("Condition records without a matching tree, sapling or shrub:"); NiceTable(Conditions_No_Plant)}
 


```

---

### Species ID

```{r Foliage_Species, echo=FALSE, hold=FALSE, results="asis"}
 
# if(nrow(Condtions_No_Name)==0) cat("All condition records have a species ID.<br>") else {
#      errorText("Condition records with no species name:"); NiceTable(Conditions_No_Name)}
#   
# if(nrow(Conditions_Wrong_Name)==0) cat("All condition records Latin names match their tree, sapling or shrub record.<br>") else {
#     errorText("Condition records whose Latin names don't match their tree, sapling or shrub:"); NiceTable(Conditions_Wrong_Name)}
# 
# if(nrow(Conditions_No_TSN)==0) cat("All condition records have a TSN.<br>") else {
#      errorText("Condition records with no TSN:"); NiceTable(Conditions_No_TSN)}
# 
# if(nrow(Conditions_Wrong_TSN)==0) cat("All condition records TSN's match their tree, sapling or shrub record.<br>") else {
#     errorText("Condition records whose TSN's don't match their tree, sapling or shrub:"); NiceTable(Conditions_Wrong_TSN)}

```

---


### Tree Foliage

```{r Plant_Foliage, echo=FALSE, hold=FALSE, results="asis"}
 
# cat("<br>**Living Tree Foliage Conditions**<br>")
#   if(nrow(Trees_Bad_Foliage_Condition)==0) cat("All live tree foliage conditions are valid. <br>") else {
#      errorText("Living tree records with invalid foliage conditions:"); NiceTable(Trees_Bad_Foliage_Condition)}
#   
# cat("<br>**Living Tree Foliage Percent**<br>")
#   if(nrow(Trees_Bad_Foliage_Condition)==0) cat("All foliage percents on live trees are valid.<br>") else {
#      errorText("Living tree records with invalid foliage percents:"); NiceTable(Trees_Bad_Foliage_Percent)}
# 
# cat("<br>**Living Redundant Foliage Condition**<br>")
#   if(nrow(Trees_Redundant_Foliage)==0) cat("No foliage conditions were repeated.<br>") else {
#      errorText("Tree records with repeated foliage conditions:"); NiceTable(Trees_Redundant_Foliage)}

# cat("<br>**Non-Living Tree Foliage Conditions**<br>")  
#   if(nrow(Trees_Unalive_Foliage)==0) cat("No non-living trees have foliage condiditons.<br>") else {
#    errorText("Non-living tree records with foliage conditions:"); NiceTable(Trees_Unalive_Foliage)}
```

---