---
title: "Forest Vegetation Quad QC"
author: "John Paul Schmit"
date: "5/19/2020"
output: html_document
---


```{r quad_setup, include=F}
TotQuads<-nrow(QCQuads) #Total Number of tree records checked

#12.1.0
Quads_Bad_Unit<-QCQuads %>% 
 filter(!Unit_Code %in% c("ANTI", "CATO", "CHOH", "GWMP", "HAFE", "MANA", "MONO", "NACE", "PRWI", "ROCR", "WOTR")) %>% 
 select(Unit_Code, Plot_Name, Quadrat_Number, Sample_Year)

Quads_Bad_Unit_Group<-QCQuads %>% 
  filter(!Unit_Group %in% c("ANTI","BOHE", "BRUN", "CATO", "CUMB", "GREE", "LOHE", "MAHE", "MANA", "MONO", "NACE", "PISC", "POGO","PRWI", "ROCR", 
                           "SHHI","SHIS","TIDE", "WILL", "WOTR")) %>% 
  select(Unit_Code, Unit_Group, Plot_Name, Quadrat_Number, Sample_Year)

Quads_Mismatch_Unit_Group<-QCQuads %>% 
  filter(Unit_Code=="ANTI" & Unit_Group!="ANTI"|
            Unit_Code=="CATO" & Unit_Group !="CATO"|
            Unit_Code=="CHOH" & !Unit_Group %in% c("BRUN", "CUMB", "POGO", "WILL") |
            Unit_Code =="GWMP" & !Unit_Group %in% c("POGO","TIDE") |
            Unit_Code =="HAFE" & !Unit_Group %in% c("BOHE", "LOHE", "MAHE","SHHI", "SHIS")|
            Unit_Code=="MANA" & Unit_Group !="MANA" |
            Unit_Code=="MONO" & Unit_Group !="MONO" |
            Unit_Code=="NACE" & !Unit_Group %in% c("GREE","NACE","PISC")|
            Unit_Code=="PRWI" & Unit_Group !="PRWI" |
            Unit_Code=="ROCR" & Unit_Group !="ROCR" |
            Unit_Code=="WOTR" & Unit_Group!="WOTR"
         ) %>% 
  select(Plot_Name, Unit_Code, Unit_Group, Quadrat_Number, Sample_Year)
  
#12.2.0

Quads_No_Plot_Name<-QCQuads %>% 
 filter(is.na(Plot_Name) | Plot_Name=="") %>% 
 select(Unit_Code, Plot_Name, Quadrat_Number, Sample_Year)


#12.3.0
Quads_Bad_Name<-QCQuads %>% filter(!Quadrat_Number %in% c("60", "180", "300", "120-3m", "120-8m", "120-13m", "240-3m", "240-8m", "240-13m",
                                                          "360-3m", "360-8m", "360-13m")) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number)

Quads_Sampled<-QCEvents %>% left_join(QCQuads, by=c("Plot_Name"="Plot_Name", "Event_Year"="Sample_Year")) %>% group_by (Plot_Name, Event_Year) %>% summarize(Quads_Sampled=length(na.omit(Quadrat_Number)), Unique_Quads=length(unique(na.omit(Quadrat_Number)))) %>% 
  filter(Quads_Sampled!=12 | Unique_Quads !=12)


Duplicate_Quads<-QCQuads %>% group_by(Plot_Name, Quadrat_Number, Sample_Year) %>% summarize(Records=n()) %>% filter(Records>1) %>% 
  select(Plot_Name, Quadrat_Number, Sample_Year, Records) %>% ungroup

## Panel Frame Cycle  
 
#12.4.0
Quads_Bad_Panel<-QCQuads%>%
 filter(!Panel %in% 1:4) %>% 
 select(Unit_Code, Plot_Name, Quadrat_Number, Sample_Year, Panel)
  
#12.5.0
Quads_Bad_Frame<-QCQuads %>%
 filter(!Frame %in% c("Park","Region")) %>% 
 select(Unit_Code, Plot_Name, Quadrat_Number, Sample_Year, Frame)

#12.6.0
Quads_Bad_Cycle<-QCQuads %>% 
 filter(!(Cycle==1 & Sample_Year %in% 2005:2009) &
     !(Cycle==2 & Sample_Year %in% 2010:2013) &
     !(Cycle==3 & Sample_Year %in% 2014:2017) &
     !(Cycle==4 & Sample_Year %in% 2018:2022)) %>% 
 select(Unit_Code,Plot_Name, Quadrat_Number,  Sample_Year, Cycle)

## Dates

#12.7.0
Quads_Bad_Date<-QCQuads %>% 
 filter(!ymd(Date) %in% QCEvents$Event_Date) %>% 
 select(Unit_Code, Plot_Name, Quadrat_Number, Sample_Year, Date)

#12.8.0
Quads_Bad_Year<-QCQuads %>% 
 filter(Sample_Year != year(ymd(Date))) %>% 
 select(Unit_Code, Plot_Name, Quadrat_Number, Sample_Year,Date)

 
#12.9.0
Quads_Percent_Trees<-QCQuads %>% filter(Percent_Trees<0 | Percent_Trees>100 | Percent_Trees=="" | is.na(Percent_Trees)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Trees)

#12.10.0
Quads_Percent_Bryophytes<-QCQuads %>% filter(Percent_Bryophytes<0 | Percent_Bryophytes>100 | Percent_Bryophytes=="" | is.na(Percent_Bryophytes)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Bryophytes)

#12.11.0
Quads_Percent_Rock<-QCQuads %>% filter(Percent_Rock<0 | Percent_Rock>100 | Percent_Rock=="" | is.na(Percent_Rock)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Rock)

#12.12.0
Quads_Percent_CWD<-QCQuads %>% filter(Percent_Coarse_Woody_Debris<0 | Percent_Coarse_Woody_Debris>100 | Percent_Coarse_Woody_Debris=="" |
                                        is.na(Percent_Coarse_Woody_Debris)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Coarse_Woody_Debris)

#12.13.0
Quads_Percent_FWD<-QCQuads %>% filter(Sample_Year>=2013, Percent_Fine_Woody_Debris<0 | Percent_Fine_Woody_Debris>100 | Percent_Fine_Woody_Debris=="" | 
                                        is.na(Percent_Fine_Woody_Debris)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Fine_Woody_Debris)

#12.14.0
Quads_Percent_Other<-QCQuads %>% filter(Percent_Other<0 | Percent_Other>100 | Percent_Other=="" | is.na(Percent_Other)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Other)

#12.15.0
Quads_Percent_Grasses<-QCQuads %>% filter(Percent_Grasses<0 | Percent_Grasses>100 | Percent_Grasses=="" | is.na(Percent_Grasses)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Grasses)

#12.16.0
Quads_Percent_Sedges<-QCQuads %>% filter(Percent_Sedges<0 | Percent_Sedges>100 | Percent_Sedges=="" | is.na(Percent_Sedges)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Sedges)

#12.17.0
Quads_Percent_Herbs<-QCQuads %>% filter(Percent_Herbs<0 | Percent_Herbs>100 | Percent_Herbs=="" | is.na(Percent_Herbs)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Herbs)

#12.18.0
Quads_Percent_Ferns<-QCQuads %>% filter(Percent_Ferns<0 | Percent_Ferns>100 | Percent_Ferns=="" | is.na(Percent_Ferns)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Ferns)

#12.19.0
Quads_Percent_Overload<-QCQuads %>% 
  mutate(Total= Percent_Trees + Percent_Rock + Percent_Coarse_Woody_Debris + Percent_Fine_Woody_Debris + Percent_Other) %>%
  filter(Total > 100) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Tree=Percent_Trees, Rock=Percent_Rock, CWD=Percent_Coarse_Woody_Debris,
         FWD=Percent_Fine_Woody_Debris,Other= Percent_Other, Total) 

## Change over Time

Repeat_Quads<-QCQuads %>%  group_by(Plot_Name, Quadrat_Number) %>% summarize(Records=n()) %>% filter(Records>1) 


#12.20.0
Quads_Percent_Trees_Changed <-if(nrow(Repeat_Quads>0)){
  Repeat_Quads %>% left_join(QCQuads) %>% 
    select(Plot_Name, Quadrat_Number, Cycle, Sample_Year, Percent_Trees) %>% 
    group_by(Plot_Name, Quadrat_Number) %>% arrange(Plot_Name, Quadrat_Number, Sample_Year) %>% 
    mutate(Start_Year=min(Sample_Year), Tree_Change=abs(as.numeric(Percent_Trees)-lead(as.numeric(Percent_Trees)))) %>% 
    filter(any(Tree_Change>10)) %>% 
   pivot_wider(id_cols=c(Plot_Name, Quadrat_Number, Start_Year), names_prefix = "Cycle ", values_from = Percent_Trees, 
               names_from = Cycle, names_sort = TRUE)
  } else data.frame()
  
#12.21.0
Quads_Percent_Rock_Changed <-if(nrow(Repeat_Quads>0)){
  Repeat_Quads %>% left_join(QCQuads) %>% 
    select(Plot_Name, Quadrat_Number, Cycle, Sample_Year, Percent_Rock) %>% 
    group_by(Plot_Name, Quadrat_Number) %>% arrange(Plot_Name, Quadrat_Number, Sample_Year) %>% 
    mutate(Start_Year=min(Sample_Year), Rock_Change=abs(as.numeric(Percent_Rock)-lead(as.numeric(Percent_Rock)))) %>% 
    filter(any(Rock_Change>10)) %>% 
   pivot_wider(id_cols=c(Plot_Name, Quadrat_Number, Start_Year), names_prefix = "Cycle ", values_from = Percent_Rock, 
               names_from = Cycle, names_sort = TRUE)
  } else data.frame()

#12.22.0
Quads_Percent_Bryophytes_Changed <-if(nrow(Repeat_Quads>0)){
  Repeat_Quads %>% left_join(QCQuads) %>% 
    select(Plot_Name, Quadrat_Number, Cycle, Sample_Year, Percent_Bryophytes) %>% 
    group_by(Plot_Name, Quadrat_Number) %>% arrange(Plot_Name, Quadrat_Number, Sample_Year) %>% 
    mutate(Start_Year=min(Sample_Year), Bryophyte_Change=abs(as.numeric(Percent_Bryophytes)-lead(as.numeric(Percent_Bryophytes)))) %>% 
    filter(any(Bryophyte_Change>15)) %>% 
   pivot_wider(id_cols=c(Plot_Name, Quadrat_Number, Start_Year), names_prefix = "Cycle ", values_from = Percent_Bryophytes, 
               names_from = Cycle, names_sort = TRUE)
  } else data.frame()

#12.23.0
Quads_Percent_Ferns_Changed <-if(nrow(Repeat_Quads>0)){
  Repeat_Quads %>% left_join(QCQuads) %>% 
    select(Plot_Name, Quadrat_Number, Cycle, Sample_Year, Percent_Ferns) %>% 
    group_by(Plot_Name, Quadrat_Number) %>% arrange(Plot_Name, Quadrat_Number, Sample_Year) %>% 
    mutate(Start_Year=min(Sample_Year), Fern_Change=abs(as.numeric(Percent_Ferns)-lead(as.numeric(Percent_Ferns)))) %>% 
    filter(any(Fern_Change>15)) %>% 
   pivot_wider(id_cols=c(Plot_Name, Quadrat_Number, Start_Year), names_prefix = "Cycle ", values_from = Percent_Ferns, 
               names_from = Cycle, names_sort = TRUE)
  } else data.frame()

#12.24.0

# Look to see if difference between years from Grass to sedge is greater than that from grass to grass, and similar for sedges

Grass_Sedge_Switched <-if(nrow(Repeat_Quads>0)){
  QCQuads %>% semi_join(Repeat_Quads) %>% 
    select(Plot_Name, Quadrat_Number, Cycle, Sample_Year, Percent_Grasses, Percent_Sedges) %>% 
    group_by(Plot_Name, Quadrat_Number) %>% arrange(Plot_Name, Quadrat_Number, Sample_Year) %>% 
    mutate(Start_Year=min(Sample_Year), 
           Grass_Grass=abs(as.numeric(Percent_Grasses)-lead(as.numeric(Percent_Grasses))),
           Sedge_Sedge=abs(as.numeric(Percent_Sedges)-lead(as.numeric(Percent_Sedges))),
           Grass_Sedge=abs(as.numeric(Percent_Grasses)-lead(as.numeric(Percent_Sedges))),
           Sedge_Grass=abs(as.numeric(Percent_Sedges)-lead(as.numeric(Percent_Grasses)))
           ) %>% 
    filter(any(abs(Grass_Grass - Grass_Sedge>5) & abs(Sedge_Sedge - Sedge_Grass>5))) %>% 
    rename(Grass=Percent_Grasses, Sedge=Percent_Sedges, Quadrat=Quadrat_Number) %>% 
   pivot_wider(id_cols=c(Plot_Name, Quadrat, Start_Year), values_from = c(Grass,Sedge), 
               names_from = Cycle, names_sort = TRUE)
  } else data.frame()


```


#### **Quadrats Checked:** `r TotQuads` ####

### Unit Codes

```{r Quad_Unit_Codes, echo=FALSE, hold=FALSE, results="asis"}
 if(nrow(Quads_Bad_Unit)==0) cat("All quadrat records have a recognized Unit Code.<br>") else {
    errortext("Quadrat records with a missing or unrecongized Unit Code:"); NiceTable(Quads_Bad_Unit)}
 
 if(nrow(Quads_Bad_Unit_Group)==0) cat("All quadrat records have a recognized Unit Group.<br>") else {
    errortext("Quadrat records with a missing or unrecongized Unit Group:"); NiceTable(Quads_Bad_Unit_Group)}
  
 if(nrow(Quads_Mismatch_Unit_Group)==0) cat("All quadrat records have Unit Group that is consistent with their Unit Code.<br>") else {
     errortext("Quadrat records with a Unit Group that is inconsistent with their Unit Code:"); NiceTable(Quads_Mismatch_Unit_Group)}

```

---

### Plot Names

```{r Quad_plot_names, echo=FALSE, hold=FALSE, results="asis"}
if(nrow(Quads_No_Plot_Name)==0) cat("All quadrat records have a Plot Name.<br>") else {
errortext("Quadrat records with a missing Plot Name:"); NiceTable(Quads_No_Plot_Name)}

```

---

###  Quadrats Sampled
```{r Quads_Sampled, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Quadrat Names**<br>") 
if(nrow(Quads_Bad_Name )==0) cat("All records have a valid quadrat name.<br>") else {
     errorText("Records without a valid quadrat name:"); NiceTable(Quads_Bad_Name)}

cat("<br>**Quadrats Sampled**<br>") 
  if(nrow(Quads_Sampled)==0) cat("All plots have exactly 12 different quadrats sampled. <br>") else {
     errorText("Plots with more or less than 12 quadrats sampled:"); NiceTable(Quads_Sampled)}

cat("<br>**Quadrats Repeated**<br>") 
  if(nrow(Duplicate_Quads)==0) cat("No quadrats were sampled twice in the same year. <br>") else {
     errorText("Quads that were sampled more than once in a single year:"); NiceTable(Duplicate_Quads)}
```

---

### Event Panel, Frame and Cycle

```{r Quad_Panel_Frame_Cycle,echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Panel Data**<br>")
if(nrow(Quads_Bad_Panel)==0) cat("Each quad record has a panel code from 1 to 4.<br>") else {
errorText("Quad records without a panel code from 1-4:"); NiceTable(Quads_Bad_Panel)}
 
cat("<br>**Frame Data**<br>")
if(nrow(Quads_Bad_Frame)==0) cat("Each quad record has a frame that is either Region or Park.<br>") else {
errorText("Quad records without a frame of either Region or Park:"); NiceTable(Quads_Bad_Frame)}

cat("<br>**Cycle Data**<br>")
if(nrow(Quads_Bad_Cycle)==0) cat("Each quad record is from a cycle that matches its event year.<br>") else {
errorText("Quad records without a cycle or with a cycle that does not match its event year:"); NiceTable(Quad_Bad_Cycle)}

```

---

###  Dates
```{r Quad_Dates, echo=FALSE, hold=FALSE, results="asis"}

if(nrow(Quads_Bad_Date)==0) cat("All quad record dates match an event date.<br>") else {
errorText("Quad records whose date does not match an event date:"); NiceTable(Quads_Bad_Date)}
 
if(nrow(Quads_Bad_Year)==0) cat("All quad record dates and sample years are consistent.<br>") else {
errorText("Quad records whose date does not match its sample year:"); NiceTable(Quads_Bad_Year)}

```


---

###  Quadrats Percent Cover
```{r Quads_Percent_Cover, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Quadrats Percent Tree Cover**<br>") 
  if(nrow(Quads_Percent_Trees)==0) cat("All quadrats have between 0 and 100% tree cover. <br>") else {
     errorText("Quadrats without 0 to 100% tree cover:"); NiceTable(Quads_Percent_Trees)}

cat("<br>**Quadrats Percent Bryophyte Cover**<br>") 
  if(nrow(Quads_Percent_Bryophytes)==0) cat("All quadrats have between 0 and 100% bryophyte cover. <br>") else {
     errorText("Quadrats without 0 to 100% bryophyte cover:"); NiceTable(Quads_Percent_Bryophytes)}

cat("<br>**Quadrats Percent Rock Cover**<br>") 
  if(nrow(Quads_Percent_Rock)==0) cat("All quadrats have between 0 and 100% rock cover. <br>") else {
     errorText("Quadrats without 0 to 100% rock cover:"); NiceTable(Quads_Percent_Rock)}

cat("<br>**Quadrats Percent Coarse Woody Debris (CWD)**<br>") 
  if(nrow(Quads_Percent_CWD)==0) cat("All quadrats have between 0 and 100% CWD cover. <br>") else {
     errorText("Quadrats without 0 to 100% CWD cover:"); NiceTable(Quads_Percent_CWD)}

cat("<br>**Quadrats Percent Fine Woody Debris (FWD)**<br>") 
  if(nrow(Quads_Percent_FWD)==0) cat("All quadrats have between 0 and 100% FWD cover. <br>") else {
     errorText("Quadrats without 0 to 100% FWD cover:"); NiceTable(Quads_Percent_FWD)}

cat("<br>**Quadrats Percent Other Cover (FWD)**<br>") 
  if(nrow(Quads_Percent_Other)==0) cat("All quadrats have between 0 and 100% other cover. <br>") else {
     errorText("Quadrats without 0 to 100% other cover:"); NiceTable(Quads_Percent_Other)}

cat("<br>**Quadrats Percent Grass Cover**<br>") 
  if(nrow(Quads_Percent_Grasses)==0) cat("All quadrats have between 0 and 100% grass cover. <br>") else {
     errorText("Quadrats without 0 to 100% grass cover:"); NiceTable(Quads_Percent_Grasses)}

cat("<br>**Quadrats Percent Sedge Cover**<br>") 
  if(nrow(Quads_Percent_Sedges)==0) cat("All quadrats have between 0 and 100% sedge cover. <br>") else {
     errorText("Quadrats without 0 to 100% sedge cover:"); NiceTable(Quads_Percent_Sedges)}

cat("<br>**Quadrats Percent Herb Cover**<br>") 
  if(nrow(Quads_Percent_Herbs)==0) cat("All quadrats have between 0 and 100% herb cover. <br>") else {
     errorText("Quadrats without 0 to 100% herb cover:"); NiceTable(Quads_Percent_Herbs)}

cat("<br>**Quadrats Percent Fern Cover**<br>") 
  if(nrow(Quads_Percent_Ferns)==0) cat("All quadrats have between 0 and 100% fern cover. <br>") else {
     errorText("Quadrats without 0 to 100% fern cover:"); NiceTable(Quads_Percent_Ferns)}

cat("<br>**Quadrats Non-Living Percent > 100**<br>") 
  if(nrow(Quads_Percent_Overload)==0) cat("All quadrats have less than 100% summed tree, rock, CWD, FWD and other cover. <br>") else {
     errorText("Quadrats with over 100% summed tree, rock, CWD, FWD and other cover:"); NiceTable(Quads_Percent_Overload)}
```

---

### **Change Over Time**

### Quadrat Ground Cover Change
```{r Quads_Ground_Cover_Change, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Quadrats Tree Change > 10%**<br>") 
if(nrow(Quads_Percent_Trees_Changed)==0) cat("No records with an unusal change in Tree Cover.<br>") else {
   errorText("Events with a Tree Cover change of more than 10% between visits."); NiceTable(Quads_Percent_Trees_Changed)}

cat("<br>**Quadrats Rock Change > 10%**<br>") 
if(nrow(Quads_Percent_Rock_Changed)==0) cat("No records with an unusal change in Rock Cover.<br>") else {
   errorText("Events with a Rock Cover change of more than 10% between visits."); NiceTable(Quads_Percent_Rock_Changed)}

cat("<br>**Quadrats Bryophyte Change > 15%**<br>") 
if(nrow(Quads_Percent_Bryophytes_Changed)==0) cat("No records with an unusal change in Bryophyte Cover.<br>") else {
   errorText("Events with a Bryophyte Cover change of more than 15% between visits."); NiceTable(Quads_Percent_Bryophytes_Changed)}

cat("<br>**Quadrats Fern Change > 15%**<br>") 
if(nrow(Quads_Percent_Ferns_Changed)==0) cat("No records with an unusal change in Fern Cover.<br>") else {
   errorText("Events with a Fern Cover change of more than 15% between visits."); NiceTable(Quads_Percent_Ferns_Changed)}


cat("<br>**Possible Confusion between Grasses and Sedges **<br>") 
if(nrow(Grass_Sedge_Switched)==0) cat("No records showed potential confusion between grasses and sedges.<br>") else {
   errorText("Records that indicate a possible confusion between grasses and sedges"); NiceTable(Grass_Sedge_Switched)}

```


