---
title: "Forest Vegetation Vine QC"
author: "John Paul Schmit"
date: "5/19/2020"
output: html_document
---


```{r vine_setup, include=F}
TotVines<-nrow(QCVines) #Total Number of tree records checked

Vines_Bad_Name<-QCVines %>% filter(Sample_Year %in% QCYears, is.na(Latin_Name) | Latin_Name == "")

Vines_Bad_Host_Name<-QCVines %>% filter(Sample_Year %in% QCYears, is.na(Host_Latin_Name) | Host_Latin_Name== "")

Vines_Bad_Tag<-QCVines %>% filter(Sample_Year %in% QCYears, is.na(Host_Tag) | Host_Tag=="" | Host_Tag<1 | Host_Tag>30000) %>%
   select(Unit_Code, Plot_Name, Sample_Year, Latin_Name, Host_Tag, Host_Latin_Name)

Vines_Redundant<-QCVines %>% filter(Sample_Year %in% QCYears) %>% 
  group_by(Host_Tag, Sample_Year) %>%  filter(n()!=n_distinct(Latin_Name)) %>%
   select(Unit_Code, Plot_Name, Sample_Year, Latin_Name, Host_Tag, Host_Latin_Name)

Vines_Bad_Host_Status<-QCVines %>% filter(Sample_Year %in% QCYears, !Host_Status %in% Live_Status) %>% 
    select(Unit_Code, Plot_Name, Sample_Year, Latin_Name, Host_Tag, Host_Latin_Name, Host_Status)

Vines_Anachronistic<-QCVines %>% filter(Sample_Year %in% QCYears, Tag_Status=="Sapling", Sample_Year<2014) %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Latin_Name, Host_Tag, Host_Latin_Name, Host_Status)
 

### Multi-Year Checks

# Challenge - makes sure trees with no vines are included!
# Repeat_V<-QCSaplings %>% group_by(Tag) %>% summarize(Records=n()) %>% filter(Records>1) %>% pull(Tag)
# 
 Vine_Number<-QCVines %>% filter(Sample_Year %in% QCYears) %>% 
   group_by(Host_Tag,Sample_Year) %>% summarize(Vine_Total=n()) %>% 
   select(Host_Tag, Sample_Year,Vine_Total)
 
Vines_Number_Changes<-left_join(QCTrees , Vine_Number,  by=c("Sample_Year"="Sample_Year", "Tag"="Host_Tag")) %>%
  filter(Status %in% Live_Status) %>% 
  mutate(Vine_Total=ifelse(is.na(Vine_Total),0, Vine_Total)) %>% 
  group_by(Tag) %>% 
  filter(length(unique(Vine_Total))!=1) %>% ungroup %>% arrange(Cycle) %>% 
  pivot_wider(id_cols=c(Tag, Latin_Name), names_from=Cycle, names_prefix="Cycle ",   values_from=Vine_Total) %>% 
  arrange(Tag)
 
```



#### **Vines Checked:** `r TotVines` ####

### Latin Name

```{r vine_name, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Vine Latin Names**<br>") 
  if(nrow(Vines_Bad_Name)==0) cat("All vine records have a Latin name.<br>") else {
     errorText("Vine records without a Latin name:"); NiceTable(Vines_Bad_Name)}

cat("<br>**Vine Host Latin Names**<br>") 
  if(nrow(Vines_Bad_Host_Name)==0) cat("All vine records have a host Latin name.<br>") else {
     errorText("Vine records without a host Latin name:"); NiceTable(Vines_Bad_Host_Name)}

```




###  Host Tag
```{r Vine_Host_Tag, echo=FALSE, hold=FALSE, results="asis"}

 if(nrow(Vines_Bad_Tag)==0) cat("All vine records have a host tag between 1 and 30,000.<br>") else {
    errorText("Vine records without a host tag between 1 and 30000:"); NiceTable(Vines_Bad_Tag)}

```

---

### Host Status

```{r Vine_Host_Status, echo=FALSE, hold=FALSE, results="asis"}

 if(nrow(Vines_Bad_Host_Status)==0) cat("All vine records are on a living host.<br>") else {
    errorText("Vine records from a non-living host:"); NiceTable(Vines_Bad_Host_Status)}

```

---

### Vines on Saplings and Shrubs

```{r Vine_Sapling_Shrub, echo=FALSE, hold=FALSE, results="asis"}

errorText("Warning: This test does not check ALL vines on saplings and shrubs, only those with a current Host Tag Status of 'Sapling'")

 if(nrow(Vines_Anachronistic)==0) cat("No vines on saplings or shrubs before 2014.<br>") else {
    errorText("Vine records from a sapling or shrub before 2014:"); NiceTable(Vines_Anachronistic)}

```


### Redundant Vines

```{r Vine_Redundant, echo=FALSE, hold=FALSE, results="asis"}

 if(nrow(Vines_Redundant)==0) cat("No vines are listed twice for the same host during the same event.<br>") else {
    errorText("Vine species listed twice from the same host during a single event.:"); NiceTable(Vines_Redundant)}

```


### **Change Over Time**

### Trees that Gained or Lost Vines

```{r Vine_Number_Change, echo=FALSE, hold=FALSE, results="asis"}

 if(nrow(Vines_Number_Changes)==0) cat("No trees gained or lost vines.<br>") else {
    errorText("Trees that gained or lost vines:"); NiceTable(Vines_Number_Changes)}

```
