---
title: "Forest Vegetation Seedling QC"
author: "John Paul Schmit"
date: "5/19/2020"
output: html_document
---


```{r seeding_setup, include=F}
TotSeeds<-nrow(QCSeedlings) #Total Number of tree records checked

#10.1.0
Seedlings_Bad_Quad<-QCSeedlings %>% filter(!Quadrat_Number %in% c("60", "180", "300", "120-3m", "120-8m", "120-13m", "240-3m", "240-8m", "240-13m",
                                                          "360-3m", "360-8m", "360-13m")) %>% 
  select(Unit_Code, Plot_Name, Quadrat_Number, Sample_Year, Latin_Name, Height)

#10.2.0
Seedlings_Bad_Name<-QCSeedlings %>% filter(is.na(Latin_Name) | Latin_Name == "")

#10.3.0
Seedlings_Bad_Height<-QCSeedlings %>% filter(is.na(Height) | Height=="" | Height<15 | Height>220) %>%
   select(Unit_Code, Plot_Name, Quadrat_Number, Sample_Year, Latin_Name, Height)

 ## Seedling Browse
 
#10.4.0
Seedlings_Bad_Browsable<-QCSeedlings %>% filter(!Browsable %in% c("Yes","No", "unk") ) %>%
   select(Unit_Code, Plot_Name, Quadrat_Number, Sample_Year, Latin_Name, Browsable, Browsed)

#10.5.0
Seedlings_Anachronistic_Browsable<-QCSeedlings %>% filter(Sample_Year<2012 & Browsable != "unk" ) %>%
    select(Unit_Code, Plot_Name, Quadrat_Number, Sample_Year, Latin_Name, Browsable, Browsed)

#10.6.0
Seedlings_Bad_Browsed<-QCSeedlings %>% filter(!Browsed %in% c("Yes","No", "unk") ) %>%
     select(Unit_Code, Plot_Name, Quadrat_Number, Sample_Year, Latin_Name, Browsable, Browsed)

#10.7.0
Seedlings_Anachronistic_Browsed<-QCSeedlings %>% filter(Sample_Year<2012 & Browsed != "unk" ) %>%
    select(Unit_Code, Plot_Name, Quadrat_Number, Sample_Year, Latin_Name, Browsable, Browsed)
 
#10.8.0
Seedlings_Illogical_Browse <- QCSeedlings %>% filter(Browsed =="Yes", Browsable == "No") %>%
   select(Unit_Code, Plot_Name, Quadrat_Number, Sample_Year, Latin_Name, Browsable, Browsed)

#10.9.0
Seedlings_Unknown_Browsable <- QCSeedlings %>% filter(Sample_Year >=2012, Browsable == "unk") %>%
   select(Unit_Code, Plot_Name, Quadrat_Number, Sample_Year, Latin_Name, Browsable, Browsed)
 
```


#### **Seedlings Checked:** `r TotSeeds` ####

### Plots and Quadrats

```{r seedling_plots, echo=FALSE, hold=FALSE, results="asis"}
if(nrow(Seedlings_Bad_Quad )==0) cat("All seedling records have a valid quadrat name.<br>") else {
     errorText("Seedling records without a valid quadrat name:"); NiceTable(Seedlings_Bad_Quad)}
```

---

### Latin Name

```{r seedling_name, echo=FALSE, hold=FALSE, results="asis"}

  if(nrow(Seedlings_Bad_Name)==0) cat("All seedling records have a Latin name.<br>") else {
     errorText("Seedling records without a Latin name:"); NiceTable(Seedlings_Bad_Name)}

```

---

### Seedling Height
```{r Seedling_Height, echo=FALSE, hold=FALSE, results="asis"}

 if(nrow(Seedlings_Bad_Height)==0) cat("All seedling records have a hegiht between 15 and 220 cm.<br>") else {
    errorText("Seedling records without a height between 15 and 220:"); NiceTable(Seedlings_Bad_Height)}

```

---

### Seedling Browse

```{r Seedling_Browse, echo=FALSE, hold=FALSE, results="asis"}
 
cat("<br>**Seedling Browsable Status Invalid**<br>") 
  if(nrow(Seedlings_Bad_Browsable)==0) cat("All seedlings have a valid browsable status.<br>") else {
     errorText("Seedling records with a browsable status other than Yes, No, or unk:"); NiceTable(Seedlings_Bad_Browsable)}
  
cat("<br>**Seedlings Anachronistic Browsable Status**<br>") 
   if(nrow(Seedlings_Anachronistic_Browsable)==0) cat("No seedling records have a browsable status before 2012.<br>") else {
      errorText("Seedling records with a browsable status before 2012:"); NiceTable(Seedlings_Anachronistic_Browsable)}

cat("<br>**Seedlings Browsed Status Invalid**<br>") 
   if(nrow(Seedlings_Bad_Browsed)==0) cat("All seedlings saplings have a valid browsed status.<br>") else {
      errorText("Seedling records with a browsed status other than unk, Yes, or No:"); NiceTable(Seedlings_Bad_Browsed)}
    
cat("<br>**Seedlings Anachronistic Browsed Status**<br>") 
   if(nrow(Seedlings_Anachronistic_Browsed)==0) cat("No seedling records have a browsed status before 2012.<br>") else {
      errorText("Seedling records with a browsed status before 2012:"); NiceTable(Seedlings_Anachronistic_Browsed)}
 
cat("<br>**Seedlings with Illogical Browsing**<br>")
    if(nrow(Seedlings_Illogical_Browse)==0) cat("No seedings have contradictory browsable and browsed status.<br>") else {
       errorText("Seedling records with a browsable status of 'No' and browsed status of 'Yes':"); NiceTable(Seedlings_Illogical_Browse)}
  
cat("<br>**Seedlings with unknown Browsable Status**<br>")
    if(nrow(Seedlings_Unknown_Browsable)==0) cat("No seedings have a browsable status of 'unk' after 2011.<br>") else {
       errorText("Seedling records with a browsable status 'unk' after 2011:"); NiceTable(Seedlings_Unknown_Browsable)}

```



