---
title: "Forest Vegetation Tree QC"
author: "John Paul Schmit"
date: "5/19/2020"
output: html_document
---


```{r tree_setup, include=F}
TotTrees<-nrow(QCTrees) #Total Number of tree records checked
TotStems<-nrow(QCStems) #Total number of stem records checked


Trees_Bad_Status<-QCTrees %>% filter(is.na(Status) | !Status %in% c(Live_Status, Dead_Status, Missing_Status, Other_Status) ) %>%
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status)

Trees_No_Name<-QCTrees %>% filter(Latin_Name=="") %>%
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name)

Trees_Bad_Tag<-QCTrees %>% filter(is.na(Tag) | Tag < 1 | Tag>30000) %>%
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name)

## Crown class

Trees_Live_Bad_Crown<-QCTrees %>% filter(Status %in% Live_Status & (Crown_Description=="" | !Crown_Description %in% 
   c("Co-dominant", "Dominant", "Edge Tree", "Intermediate", "Light Gap Exploiter", "Open-grown", "Overtopped" ))) %>%
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, Crown_Description)

Trees_Unalive_Bad_Crown<-QCTrees %>% filter(!Status %in% Live_Status & Crown_Description!="") %>%
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, Crown_Description)



## DBH
Trees_Bad_DBH_Check <-QCTrees %>% filter( (Sample_Year<2018 & DBH_Check) | 
      (Sample_Year>2017 & DBH_Check & 
          Status %in% c(Missing_Status, "Dead Fallen", "Dead Missing", "Dead - Too Small", Other_Status))) %>% 
    select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, DBH_Check)

Trees_Live_Bad_DBH<-QCTrees %>% filter(Status %in% Live_Status & (
   (is.na(Equiv_Live_DBH_cm) | Equiv_Live_DBH_cm < 10 | is.na(Equiv_Dead_DBH_cm) | ( Equiv_Dead_DBH_cm>0 & Equiv_Dead_DBH_cm < 10)) ))  %>% 
   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, Equiv_Live_DBH_cm, Equiv_Dead_DBH_cm)

Trees_Dead_Bad_DBH<-QCTrees %>% filter(Status %in% c("Dead Leaning", "Dead Standing") & (
   (is.na(Equiv_Dead_DBH_cm) | Equiv_Dead_DBH_cm < 10 | is.na(Equiv_Live_DBH_cm) | Equiv_Live_DBH_cm>=10 |
      ( Equiv_Live_DBH_cm >0 & Equiv_Live_DBH_cm < 1)) ))  %>% 
   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, Equiv_Live_DBH_cm, Equiv_Dead_DBH_cm)

Trees_Other_Bad_DBH<-QCTrees %>% filter(Status %in% c(Missing_Status, Other_Status, 
    "Dead", "Dead - Human Action", "Dead - Too Small", "Dead Fallen", "Dead Missing") & (
   (is.na(Equiv_Dead_DBH_cm) |is.na(Equiv_Live_DBH_cm) | Equiv_Live_DBH_cm!=0 |
       Equiv_Dead_DBH_cm !=0 )) )  %>% 
   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, Equiv_Live_DBH_cm, Equiv_Dead_DBH_cm)

Tree_Stems_Live_Bad_DBH<-QCStems %>% filter(Sample_Year %in% QCYears, Live==T, Class=="Tree", (is.na(DBH) | DBH<1)) %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, DBH, Live )

Tree_Stems_Dead_Bad_DBH<-QCStems %>% filter(Sample_Year %in% QCYears, Live==F,  Class=="Tree", (is.na(DBH) | DBH<10)) %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, DBH, Live )

Tree_Stems_Other_Bad_DBH<-QCStems %>% filter(Sample_Year %in% QCYears, Class=="Tree", Status %in% c(Missing_Status, Other_Status, 
    "Dead", "Dead - Human Action", "Dead - Too Small", "Dead Fallen", "Dead Missing")) %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, DBH, Live )

Trees_Live_Bad_Vigor<-QCTrees %>% filter(Status %in% Live_Status & 
      ( (Sample_Year<2017 & !is.na(TreeVigor)) | (Sample_Year >=2017 & (is.na(TreeVigor)  | !TreeVigor %in% 0:5)) )) %>% 
   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, TreeVigor, VigorClass)

## Vigor
Trees_Unalive_Bad_Vigor<-QCTrees %>% filter(!Status %in% Live_Status & !is.na(TreeVigor)) %>% 
   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, TreeVigor, VigorClass)

## Foliage
Trees_Bad_Foliage_Condition<-QCFoliage %>% filter(Sample_Year  %in% QCYears & (is.na(Condition_Description) | 
              !Condition_Description %in% c("Chlorosis","Holes","Necrosis","Small leaves","Wilting","Other") )) %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Condition_Description, Percent_Afflicted)
  

Trees_Bad_Foliage_Percent<-QCFoliage %>% filter(Sample_Year  %in% QCYears & (is.na(Percent_Afflicted) | 
                            Percent_Afflicted<1 |Percent_Afflicted>100)) %>% 
    select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Condition_Description, Percent_Afflicted)

Trees_Unalive_Foliage<- QCFoliage %>% filter(Sample_Year %in% QCYears & !Status %in% Live_Status ) %>% 
    select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, Condition_Description, Percent_Afflicted)


## Tree Conditions
Trees_Live_Bad_Tree_Condition<-QCConditions %>% filter( (Sample_Year %in% QCYears) & !Pest & (Status %in% Live_Status) &
  !Condition %in% c("Advanced decay", "Primary branch broken",  "Large dead branches", "Lightning Damage", "Wind Damage", "Buck Rub", "Bark Damage",
                    "Beaver Damage", "Human Damage", "Mammal Damage", "Bird Damage", "Exposed roots", "Epicormic sprouts", "Fungus", "Fire", "Hollow",
                    "Sparse foliage", "Open wound", "Vines in the crown",  "Vine stress", "Other visible condition", "Other visible damage")) %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Condition)

Trees_Live_Anachronistic_Tree_Conditions<-QCConditions %>% filter( (Sample_Year %in% QCYears) & !Pest & (Status %in% Live_Status) &
      (
        (Condition =="Lightning Damage" & Sample_Year< 2009) | 
          (Condition %in% c("Buck Rub", "Bark Damage", "Human Damage") & Sample_Year < 2014) |
          (Condition =="Beaver Damage" & !Sample_Year %in% 2014:2016) |
          (Condition =="Epicormic Sprouts" & Sample_Year< 2015) |
          (Condition %in% c("Mammal Damage", "Bird Damage", "Exposed roots", "Fungus", "Fire", "Hollow", "Sparse foliage",
                            "Other visible condition") & Sample_Year < 2017) |
          (Condition =="Vine Stress" & Sample_Year< 2015) |
         (Condition =="Other visible damage" & Sample_Year> 2016)
        )) %>%   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Condition)


Trees_Unalive_Tree_Conditions<-QCConditions %>% filter( (Sample_Year %in% QCYears) & !Pest & 
                (Status %in% c(Dead_Status, Missing_Status, Other_Status))) %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, Condition)

## Tree Pests

Trees_Live_Bad_Pest<-QCConditions %>% filter( (Sample_Year %in% QCYears) & Pest & (Status %in% Live_Status) &
  !Condition %in% c("Asian longhorned beetle", "Beech bark disease",  "Butternut canker", "Chestnut blight", "Dogwood anthracnose", 
                    "Emerald ash borer", "Gypsy moth","Hemlock Scale", "Hemlock wooly adelgid", "Oak wilt", "Spotted lanternfly", 
                    "Thousand cankers disease", "Tent caterpillars", "Other significant insect damage")) %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Condition)

Trees_Live_Anachronistic_Pest<-QCConditions %>% filter( (Sample_Year %in% QCYears) & Pest & (Status %in% Live_Status) &
      (
        (Condition %in% c("Dogwood anthracnose","Hemlock Scale") & Sample_Year< 2008) | 
          (Condition =="Emrerald ash borer" & Sample_Year < 2009) |
          (Condition %in% c("Asian longhotnrf beetle","Chestnut blight", "Oak wilt", "Thousand cankers disease") & Sample_Year < 2014) |
          (Condition =="Tent caterpillars" & Sample_Year< 2017) |
          (Condition =="Spotted lanternfly" & Sample_Year < 2018))
    ) %>%   select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Condition)


Trees_Unalive_Pest<-QCConditions %>% filter( (Sample_Year %in% QCYears) & Pest & Condition !="Emerald ash borer" &
                (Status %in% c(Dead_Status, Missing_Status, Other_Status) )) %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, Condition)

Trees_Pest_Bad_Host<-QCConditions %>% filter((Sample_Year %in% QCYears) & Pest & 
  (
   (Condition == "Beach bark disease" & Latin_Name !="Fagus grandifolia") |
    (Condition =="Butternut canker" & Latin_Name != "Junglans cinerea") |
    (Condition == "Chestnut blight" & Latin_Name != "Castanea dentata") |
    (Condition == "Dogwood anthracnose" & Latin_Name != "Cornus florida") |
    (Condition =="Emerald ash borer" & !Latin_Name %in% c("Fraxinus americana", "Fraxinus nigra", "Fraxinus pennsylvanica", "Fraxinus profunda")) |
    (Condition %in% c("Hemlock Scale", "Hemlock wooly adelgid") & Latin_Name != "Tsuga canadensis") |
    (Condition =="Thousand cankers disease" & Latin_Name !="Juglans nigra")
  )) %>% select(Unit_Code, Plot_Name, Sample_Year, Tag, Latin_Name, Status, Condition)

Trees_Bad_Vines<-QCConditions %>% filter((Sample_Year %in% QCYears) & Condition=="Vines in the crown")%>% 
  left_join(QCVines %>% select(Plot_Name,Sample_Year,Tag=Host_Tag, Vine= Latin_Name )) %>% 
  filter(is.na(Vine) | Vine=="") %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Tag, Status,  Condition, Vine)


### Multi-Year Checks

Repeat_Trees<-QCTrees %>% group_by(Tag) %>% summarize(Records=n()) %>% filter(Records>1) %>% pull(Tag)

Trees_Start_Wrong<-if(length(Repeat_Trees>0)){
  QCTrees %>% filter(Tag %in% Repeat_Trees) %>% 
  group_by(Tag) %>% arrange(Tag, Sample_Year) %>% 
  filter(any(Sample_Year==min(Sample_Year) & (Status  %in% c(Missing_Status, Other_Status, "Dead Fallen")) | 
           (Status %in% Dead_Status & Sample_Year < 2010 )) ) %>% 
  mutate(Start_Year=min(Sample_Year)) %>% 
  select(Plot_Name, Cycle, Tag, Latin_Name, Status, Start_Year) %>% 
    pivot_wider(id_cols=c(Plot_Name, Tag, Latin_Name, Start_Year) , names_from = Cycle, 
                names_prefix = "Cycle ", values_from = Status)} else data.frame()

Trees_Dead_Fallen_Plus<-if(length(Repeat_Trees>0)){
  QCTrees %>% filter(Tag %in% Repeat_Trees) %>% 
  group_by(Tag) %>% arrange(Tag, Sample_Year) %>% 
  filter(any(Sample_Year!=max(Sample_Year) & Status=="Dead FAllen")) %>% 
  mutate(Start_Year=min(Sample_Year)) %>% 
   select(Plot_Name, Cycle, Sample_Year, Tag, Latin_Name, Status, Start_Year) %>% 
   pivot_wider(id_cols = c(Plot_Name, Tag, Latin_Name, Start_Year), names_prefix = "Cycle ",
               values_from = Status, names_from = Cycle ) } else data.frame()

Trees_Reanimated<-if(length(Repeat_Trees>0)){
  QCTrees %>% filter(Tag %in% Repeat_Trees) %>% 
  group_by(Tag) %>% arrange(Tag, Sample_Year) %>% 
  filter(any(Status %in% Dead_Status & lead(Status) %in% c(Live_Status, Other_Status, Missing_Status ))) %>% 
  mutate(Start_Year=min(Sample_Year)) %>% 
   select(Plot_Name, Cycle, Sample_Year, Tag, Latin_Name, Status, Start_Year) %>% 
   pivot_wider(id_cols = c(Plot_Name, Tag, Latin_Name, Start_Year), names_prefix = "Cycle ",
               values_from = Status, names_from = Cycle ) } else data.frame()
  
Trees_Levitated<-if(length(Repeat_Trees>0)){
  QCTrees %>% filter(Tag %in% Repeat_Trees) %>% 
  group_by(Tag) %>% arrange(Tag, Sample_Year) %>% 
  filter(any(Status =="Alive Fallen" & lead(Status) %in% c("Alive Broken", "Alive Leaning", "Alive Standing",
                                                           "Dead Leaning", "Dead Standing"))) %>% 
  mutate(Start_Year=min(Sample_Year)) %>% 
   select(Plot_Name, Cycle, Sample_Year, Tag, Latin_Name, Status, Start_Year) %>% 
   pivot_wider(id_cols = c(Plot_Name, Tag, Latin_Name, Start_Year), names_prefix = "Cycle ",
               values_from = Status, names_from = Cycle ) } else data.frame()

Trees_Found_Alive<-if(length(Repeat_Trees>0)){
  QCTrees %>% filter(Tag %in% Repeat_Trees) %>% 
  group_by(Tag) %>% arrange(Tag, Sample_Year) %>% 
  filter(any( (Status %in% Missing_Status) & (lead(Status) %in% Live_Status) )) %>% 
  mutate(Start_Year=min(Sample_Year)) %>% 
   select(Plot_Name, Cycle, Sample_Year, Tag, Latin_Name, Status, Start_Year) %>% 
   pivot_wider(id_cols = c(Plot_Name, Tag, Latin_Name, Start_Year), names_prefix = "Cycle ",
               values_from = Status, names_from = Cycle ) } else data.frame()


```


- dead trees wth > 1cm live dbh should not exist in a microplot as it would be a sapling (need distance / azimuht)

#### **Trees Checked:** `r TotTrees` ####
#### **Stems Checked:** `r TotStems` ####

###  Tree Status
```{r Tree_Status, echo=FALSE, hold=FALSE, results="asis"}

if(nrow(Trees_Bad_Status)==0) cat("All tree records checked have a valid status.<br>") else {
   errorText("Tree records without a status or a status we do not use:"); NiceTable(Trees_Bad_Status)}

```

---

### Species ID

```{r Tree_Species, echo=FALSE, hold=FALSE, results="asis"}
 
 if(nrow(Trees_No_Name)==0) cat("All tree records checked have a species ID.<br>") else {
    errorText("Tree records with no species name:"); NiceTable(Trees_No_Name)}

```


---

### Tree Tag

```{r Tree_Tag, echo=FALSE, hold=FALSE, results="asis"}
 if(nrow(Trees_Bad_Tag)==0) cat("All tree records have a valid tag.<br>") else {
    errorText("Tree records with no tag or a tag <1 or >30,000 tag:"); NiceTable(Trees_Bad_Tag)}

```

---

### Tree Crown

```{r Tree_Crown, echo=FALSE, hold=FALSE, results="asis"}
 cat("<br>**Living Trees' Crown Description**<br>")
 if(nrow(Trees_Live_Bad_Crown)==0) cat("All tree records have a valid crown description.<br>") else {
    errorText("Living Tree records with a mising crown description or one we do not use:"); NiceTable(Trees_Live_Bad_Crown)}

cat("<br>**Non-Living Trees' Crown Description**<br>")
 if(nrow(Trees_Unalive_Bad_Crown)==0) cat("All tree records checked and no non-living trees have a crown description.<br>") else { 
    errorText("Non-living tree records with a crown description:"); NiceTable(Trees_Unalive_Bad_Crown)}
```

---

### Tree Diameter

```{r Tree_Diameter, echo=FALSE, hold=FALSE, results="asis"}
cat("<br>**DBH Check**<br>")
 if(nrow(Trees_Bad_DBH_Check)==0) cat("No tree records have an inappropriate DBH check.<br>") else { 
    errorText("Tree records with the DBH check box checked before that was done or for tree with no DBH:"); NiceTable(Trees_Bad_DBH_Check)}

cat("<br>**Living Tree DBH Incorrect**<br>")
 if(nrow(Trees_Live_Bad_DBH)==0) cat("No live tree records have an invlid DBH.<br>") else { 
    errorText("Live tree records with a living or dead DBH < 10cm:"); NiceTable(Trees_Live_Bad_DBH)}

cat("<br>**Dead Tree DBH Incorrect**<br>") 
if(nrow(Trees_Dead_Bad_DBH)==0) cat(" No dead tree records have an invlid DBH.<br>") else { 
    errorText("Dead tree records with a dead DBH <10cm:"); NiceTable(Trees_Dead_Bad_DBH)}

cat("<br>**DBH Wrongly Recorded**<br>")
if(nrow(Trees_Other_Bad_DBH)==0) cat("No tree records have a DBH when they should not.<br>") else { 
    errorText("Tree records with a DBH that should not have one:"); NiceTable(Trees_Other_Bad_DBH)}

```

---


### Stem Diameter

```{r Tree_Stem_Diameter, echo=FALSE, hold=FALSE, results="asis"}
cat("<br>**Living Stem DBH Incorrect**<br>")
 if(nrow(Tree_Stems_Live_Bad_DBH)==0) cat("No live tree stems have an invlid DBH.<br>") else { 
    errorText("Live tree stem records with a missing DBH or a DBH <1 cm:"); NiceTable(Tree_Stems_Live_Bad_DBH)}

cat("<br>**Dead Stem DBH Incorrect**<br>")
 if(nrow(Tree_Stems_Dead_Bad_DBH)==0) cat("No dead tree stems have an invlid DBH.<br>") else { 
    errorText("Dead tree stem records with a missing DBH or a DBH <10 cm:"); NiceTable(Tree_Stems_Dead_Bad_DBH)}

cat("<br>**Stem DBH Wrongly Recorded**<br>") 
 if(nrow(Tree_Stems_Other_Bad_DBH)==0) cat("Mo tree stems have a DBH when they should not.<br>") else { 
    errorText("Tree stem records with a DBH on a tree that should not have any DBH:"); NiceTable(Tree_Stems_Other_Bad_DBH)}

```

---

### Tree Vigor

```{r Tree_vigor, echo=FALSE, hold=FALSE, results="asis"}
 
cat("<br>**Living Tree Vigor Invalid**<br>")
 if(nrow(Trees_Live_Bad_Vigor)==0) cat("All live trees have a valid vigor.<br>") else {
    errorText("Living tree records with a vigor other than 0-5:"); NiceTable(Trees_Live_Bad_Vigor)}

cat("<br>**Non-Living Trees with Vigor**<br>")
 if(nrow(Trees_Unalive_Bad_Vigor)==0) cat("No non-living trees have a vigor.<br>") else {
    errorText("Non-living tree records with a vigor:"); NiceTable(Trees_Unalive_Bad_Vigor)}

```

---

### Tree Foliage

```{r Tree_Foliatge, echo=FALSE, hold=FALSE, results="asis"}
 
cat("<br>**Living Tree Foliage Conditions**<br>")
  if(nrow(Trees_Bad_Foliage_Condition)==0) cat("All live tree foliage conditions are valid. <br>") else {
     errorText("Living tree records with invalid foliage conditions:"); NiceTable(Trees_Bad_Foliage_Condition)}
  
cat("<br>**Living Tree Foliage Percent**<br>")
  if(nrow(Trees_Bad_Foliage_Condition)==0) cat("All foliage percents on live trees are valid.<br>") else {
     errorText("Living tree records with invalid foliage percents:"); NiceTable(Trees_Bad_Foliage_Percent)}

cat("<br>**Non-Living Tree Foliage Conditions**<br>")  
  if(nrow(Trees_Unalive_Foliage)==0) cat("No non-living trees have foliage condiditons.<br>") else {
     errorText("Non-living tree records with foliage conditions:"); NiceTable(Trees_Unalive_Foliage)}
```

---

### Tree Conditions

```{r Tree_Conditions, echo=FALSE, hold=FALSE, results="asis"}
 
cat("<br>**Living Tree Conditions**<br>")
if(nrow(Trees_Live_Bad_Tree_Condition)==0) cat("All tree conditions are valid.") else {
     errorText("Living tree records with a tree condition we don't monitor:"); NiceTable(Trees_Live_Bad_Tree_Condition)}

cat("<br>**Anachronistic Tree Conditions**<br>")
if(nrow(Trees_Live_Anachronistic_Tree_Conditions)==0) cat("All tree conditions are from the correct year.<br>") else {
  errorText("Living tree records with a tree condition from the wrong year:"); NiceTable(Trees_Live_Anachronistic_Tree_Conditions)}

cat("<br>**Non-Living Tree Conditions**<br>")
if(nrow(Trees_Unalive_Tree_Conditions)==0) cat("No non-living trees have tree-conditions.<br>") else { 
  errorText("Non-living tree records with a tree condition:"); NiceTable(Trees_Unalive_Tree_Conditions)}

cat("<br>**Vines in the Crown vs. Vines**<br>")
if(nrow(Trees_Bad_Vines)==0) cat("All tree records with vines in the crown had vine species recorded.<br>") else { 
  errorText("Tree records with vines in the crown but no corresponding vine record:"); NiceTable(Trees_Bad_Vines)}
```

---

### Tree Pests

```{r Tree_Pests, echo=FALSE, hold=FALSE, results="asis"}
 
cat("<br>**Living Tree Pests**<br>")
if(nrow(Trees_Live_Bad_Pest)==0) cat("All pest records from live trees are valid.<br>") else {
     errorText("Living tree records with a pest we don't monitor:"); NiceTable(Trees_Live_Bad_Pest)}

cat("<br>**Anachronistic Pests**<br>") 
 if(nrow(Trees_Live_Anachronistic_Pest)==0) cat("No pests recorded before we started monitoring them.<br>") else {
   errorText("Living tree records with a pest from the wrong year:"); NiceTable(Trees_Live_Anachronistic_Pest)}
 
cat("<br>**Non-Living Tree Pests**<br>")
 if(nrow(Trees_Unalive_Pest)==0) cat("No non-living trees have pests (except for EAB).<br>") else {
   errorText("Non-living tree records with a pest other than EAB:"); NiceTable(Trees_Unalive_Pest)}

cat("<br>**Mis-matched Tree Pests**<br>")
 if(nrow(Trees_Pest_Bad_Host)==0) cat("No pests on incorrect host species.<br>") else {
   errorText("Trees with inconsistent host species - pest pairs:"); NiceTable(Trees_Pest_Bad_Host)}

```

---

### **Change Over Time**

### Tree Status Discrepancies

```{r Tree_Status_Change, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Trees that Start in a Non-Sampled Status**<br>")
 if(nrow(Trees_Start_Wrong)==0) cat("No tree start as missing downgraded, or dead fallen.<br>") else {
   errorText("Trees that start in a non-sampled status:"); NiceTable(Trees_Start_Wrong)}

cat("<br>**Trees that are Sampled after they are Dead Fallen**<br>")
 if(nrow(Trees_Dead_Fallen_Plus)==0) cat("No tree is sampled after it is dead fallen.<br>") else {
   errorText("Trees that are sampled after they are dead fallen:"); NiceTable(Trees_Dead_Fallen_Plus)}

cat("<br>**Trees that have Risen from the Dead**<br>")
 if(nrow(Trees_Reanimated)==0) cat("No tree was reanimated after it died.<br>") else {
   errorText("Trees that died but did not stay dead:"); NiceTable(Trees_Reanimated)}

cat("<br>**Trees Fell Down and then Levitated Back Up**<br>")
 if(nrow(Trees_Levitated)==0) cat("No tree was Alive Fallen and then became Standing or Leaning.<br>") else {
   errorText("Trees that were Alive Fallen but then became Standing or Leaning:"); NiceTable(Trees_Levitated)}

cat("<br>**Trees that were Lost and Found Alive**<br>")
 if(nrow(Trees_Found_Alive)==0) cat("No tree was Missing and then found Alive.<br>") else {
   errorText("Trees that were Missing but then were found Alive:"); NiceTable(Trees_Found_Alive)}

```
