---
title: "Forest Vegetation Quad QC"
author: "John Paul Schmit"
date: "5/19/2020"
output: html_document
---


```{r quad_setup, include=F}
TotQuads<-nrow(QCQuads) #Total Number of tree records checked

#9.1.0

##                    CHECK THIS !!!!!!!!!!!! DOES NOT TAKE YEAR INTO ACCOUNT
Repeat_Quads<-QCQuads %>% group_by(Plot_Name, Quadrat_Number) %>% summarize(Visits=n()) %>% filter(Visits>1) %>% 
  select(Plot_Name, Quadrat_Number) %>% ungroup

#9.2.0
Quads_Bad_Name<-QCQuads %>% filter(!Quadrat_Number %in% c("60", "180", "300", "120-3m", "120-8m", "120-13m", "240-3m", "240-8m", "240-13m",
                                                          "360-3m", "360-8m", "360-13m")) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number)

#9.3.0
Quads_Sampled<-QCEvents %>% left_join(QCQuads, by=c("Plot_Name"="Plot_Name", "Event_Year"="Sample_Year")) %>% group_by (Plot_Name, Event_Year) %>% summarize(Quads_Sampled=length(na.omit(Quadrat_Number)), Unique_Quads=length(unique(na.omit(Quadrat_Number)))) %>% 
  filter(Quads_Sampled!=12 | Unique_Quads !=12) 

#9.4.0
Quads_Percent_Trees<-QCQuads %>% filter(Percent_Trees<0 | Percent_Trees>100 | Percent_Trees=="" | is.na(Percent_Trees)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Trees)

#9.5.0
Quads_Percent_Bryophytes<-QCQuads %>% filter(Percent_Bryophytes<0 | Percent_Bryophytes>100 | Percent_Bryophytes=="" | is.na(Percent_Bryophytes)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Bryophytes)

#9.6.0
Quads_Percent_Rock<-QCQuads %>% filter(Percent_Rock<0 | Percent_Rock>100 | Percent_Rock=="" | is.na(Percent_Rock)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Rock)

#9.7.0
Quads_Percent_CWD<-QCQuads %>% filter(Percent_Coarse_Woody_Debris<0 | Percent_Coarse_Woody_Debris>100 | Percent_Coarse_Woody_Debris=="" |
                                        is.na(Percent_Coarse_Woody_Debris)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Coarse_Woody_Debris)

#9.8.0
Quads_Percent_FWD<-QCQuads %>% filter(Percent_Fine_Woody_Debris<0 | Percent_Fine_Woody_Debris>100 | Percent_Fine_Woody_Debris=="" | 
                                        is.na(Percent_Fine_Woody_Debris)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Fine_Woody_Debris)

#9.9.0
Quads_Percent_Other<-QCQuads %>% filter(Percent_Other<0 | Percent_Other>100 | Percent_Other=="" | is.na(Percent_Other)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Other)

#9.10.0
Quads_Percent_Grasses<-QCQuads %>% filter(Percent_Grasses<0 | Percent_Grasses>100 | Percent_Grasses=="" | is.na(Percent_Grasses)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Grasses)

#9.11.0
Quads_Percent_Sedges<-QCQuads %>% filter(Percent_Sedges<0 | Percent_Sedges>100 | Percent_Sedges=="" | is.na(Percent_Sedges)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Sedges)

#9.12.0
Quads_Percent_Herbs<-QCQuads %>% filter(Percent_Herbs<0 | Percent_Herbs>100 | Percent_Herbs=="" | is.na(Percent_Herbs)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Herbs)

#9.13.0
Quads_Percent_Ferns<-QCQuads %>% filter(Percent_Ferns<0 | Percent_Ferns>100 | Percent_Ferns=="" | is.na(Percent_Ferns)) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Percent_Ferns)

#9.14.0
Quads_Percent_Overload<-QCQuads %>% 
  mutate(Total= Percent_Trees + Percent_Rock + Percent_Coarse_Woody_Debris + Percent_Fine_Woody_Debris + Percent_Other) %>%
  filter(Total > 100) %>% 
  select(Plot_Name, Sample_Year, Quadrat_Number, Tree=Percent_Trees, Rock=Percent_Rock, CWD=Percent_Coarse_Woody_Debris,
         FWD=Percent_Fine_Woody_Debris,Other= Percent_Other, Total) 

#9.15.0
Quads_Percent_Trees_Changed <-if(nrow(Repeat_Quads>0)){
  Repeat_Quads %>% left_join(QCQuads) %>% 
    select(Plot_Name, Quadrat_Number, Cycle, Sample_Year, Percent_Trees) %>% 
    group_by(Plot_Name, Quadrat_Number) %>% arrange(Plot_Name, Quadrat_Number, Sample_Year) %>% 
    mutate(Start_Year=min(Sample_Year), Tree_Change=abs(as.numeric(Percent_Trees)-lead(as.numeric(Percent_Trees)))) %>% 
    filter(any(Tree_Change>10)) %>% 
   pivot_wider(id_cols=c(Plot_Name, Quadrat_Number, Start_Year), names_prefix = "Cycle ", values_from = Percent_Trees, 
               names_from = Cycle, names_sort = TRUE)
  } else data.frame()
  
#9.16.0
Quads_Percent_Rock_Changed <-if(nrow(Repeat_Quads>0)){
  Repeat_Quads %>% left_join(QCQuads) %>% 
    select(Plot_Name, Quadrat_Number, Cycle, Sample_Year, Percent_Rock) %>% 
    group_by(Plot_Name, Quadrat_Number) %>% arrange(Plot_Name, Quadrat_Number, Sample_Year) %>% 
    mutate(Start_Year=min(Sample_Year), Rock_Change=abs(as.numeric(Percent_Rock)-lead(as.numeric(Percent_Rock)))) %>% 
    filter(any(Rock_Change>10)) %>% 
   pivot_wider(id_cols=c(Plot_Name, Quadrat_Number, Start_Year), names_prefix = "Cycle ", values_from = Percent_Rock, 
               names_from = Cycle, names_sort = TRUE)
  } else data.frame()

#9.17.0
Quads_Percent_Bryophytes_Changed <-if(nrow(Repeat_Quads>0)){
  Repeat_Quads %>% left_join(QCQuads) %>% 
    select(Plot_Name, Quadrat_Number, Cycle, Sample_Year, Percent_Bryophytes) %>% 
    group_by(Plot_Name, Quadrat_Number) %>% arrange(Plot_Name, Quadrat_Number, Sample_Year) %>% 
    mutate(Start_Year=min(Sample_Year), Bryophyte_Change=abs(as.numeric(Percent_Bryophytes)-lead(as.numeric(Percent_Bryophytes)))) %>% 
    filter(any(Bryophyte_Change>15)) %>% 
   pivot_wider(id_cols=c(Plot_Name, Quadrat_Number, Start_Year), names_prefix = "Cycle ", values_from = Percent_Bryophytes, 
               names_from = Cycle, names_sort = TRUE)
  } else data.frame()

# Quads_Percent_Herbs_Changed <-if(nrow(Repeat_Quads>0)){
#   Repeat_Quads %>% left_join(QCQuads) %>% 
#     select(Plot_Name, Quadrat_Number, Cycle, Sample_Year, Percent_Herbs) %>% 
#     group_by(Plot_Name, Quadrat_Number) %>% arrange(Plot_Name, Quadrat_Number, Sample_Year) %>% 
#     mutate(Start_Year=min(Sample_Year), Herb_Change=abs(as.numeric(Percent_Herbs)-lead(as.numeric(Percent_Herbs)))) %>% 
#     filter(any(Herb_Change>15)) %>% 
#    pivot_wider(id_cols=c(Plot_Name, Quadrat_Number, Start_Year), names_prefix = "Cycle ", values_from = Percent_Herbs, 
#                names_from = Cycle, names_sort = TRUE)
#   } else data.frame()

#9.18.0
Quads_Percent_Ferns_Changed <-if(nrow(Repeat_Quads>0)){
  Repeat_Quads %>% left_join(QCQuads) %>% 
    select(Plot_Name, Quadrat_Number, Cycle, Sample_Year, Percent_Ferns) %>% 
    group_by(Plot_Name, Quadrat_Number) %>% arrange(Plot_Name, Quadrat_Number, Sample_Year) %>% 
    mutate(Start_Year=min(Sample_Year), Fern_Change=abs(as.numeric(Percent_Ferns)-lead(as.numeric(Percent_Ferns)))) %>% 
    filter(any(Fern_Change>15)) %>% 
   pivot_wider(id_cols=c(Plot_Name, Quadrat_Number, Start_Year), names_prefix = "Cycle ", values_from = Percent_Ferns, 
               names_from = Cycle, names_sort = TRUE)
  } else data.frame()

```


#### **Quadrats Checked:** `r TotQuads` ####

###  Quadrats Sampled
```{r Quads_Sampled, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Quadrat Names**<br>") 
if(nrow(Quads_Bad_Name )==0) cat("All records have a valid quadrat name.<br>") else {
     errorText("Records without a valid quadrat name:"); NiceTable(Quads_Bad_Name)}

cat("<br>**Quadrats Sampled**<br>") 
  if(nrow(Quads_Sampled)==0) cat("All plots have exactly 12 different quadrats sampled. <br>") else {
     errorText("Plots with more or less than 12 quadrats sampled:"); NiceTable(Quads_Sampled)}



```

---

###  Quadrats Percent Cover
```{r Quads_Percent_Cover, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Quadrats Percent Tree Cover**<br>") 
  if(nrow(Quads_Percent_Trees)==0) cat("All quadrats have between 0 and 100% tree cover. <br>") else {
     errorText("Quadrats without 0 to 100% tree cover:"); NiceTable(Quads_Percent_Trees)}

cat("<br>**Quadrats Percent Bryophyte Cover**<br>") 
  if(nrow(Quads_Percent_Bryophytes)==0) cat("All quadrats have between 0 and 100% bryophyte cover. <br>") else {
     errorText("Quadrats without 0 to 100% bryophyte cover:"); NiceTable(Quads_Percent_Bryophytes)}

cat("<br>**Quadrats Percent Rock Cover**<br>") 
  if(nrow(Quads_Percent_Rock)==0) cat("All quadrats have between 0 and 100% rock cover. <br>") else {
     errorText("Quadrats without 0 to 100% rock cover:"); NiceTable(Quads_Percent_Rock)}

cat("<br>**Quadrats Percent Coarse Woody Debris (CWD)**<br>") 
  if(nrow(Quads_Percent_CWD)==0) cat("All quadrats have between 0 and 100% CWD cover. <br>") else {
     errorText("Quadrats without 0 to 100% CWD cover:"); NiceTable(Quads_Percent_CWD)}

cat("<br>**Quadrats Percent Fine Woody Debris (FWD)**<br>") 
  if(nrow(Quads_Percent_FWD)==0) cat("All quadrats have between 0 and 100% FWD cover. <br>") else {
     errorText("Quadrats without 0 to 100% FWD cover:"); NiceTable(Quads_Percent_FWD)}

cat("<br>**Quadrats Percent Other Cover (FWD)**<br>") 
  if(nrow(Quads_Percent_Other)==0) cat("All quadrats have between 0 and 100% other cover. <br>") else {
     errorText("Quadrats without 0 to 100% other cover:"); NiceTable(Quads_Percent_Other)}

cat("<br>**Quadrats Percent Grass Cover**<br>") 
  if(nrow(Quads_Percent_Grasses)==0) cat("All quadrats have between 0 and 100% grass cover. <br>") else {
     errorText("Quadrats without 0 to 100% grass cover:"); NiceTable(Quads_Percent_Grasses)}

cat("<br>**Quadrats Percent Sedge Cover**<br>") 
  if(nrow(Quads_Percent_Sedges)==0) cat("All quadrats have between 0 and 100% sedge cover. <br>") else {
     errorText("Quadrats without 0 to 100% sedge cover:"); NiceTable(Quads_Percent_Sedges)}

cat("<br>**Quadrats Percent Herb Cover**<br>") 
  if(nrow(Quads_Percent_Herbs)==0) cat("All quadrats have between 0 and 100% herb cover. <br>") else {
     errorText("Quadrats without 0 to 100% herb cover:"); NiceTable(Quads_Percent_Herbs)}

cat("<br>**Quadrats Percent Fern Cover**<br>") 
  if(nrow(Quads_Percent_Ferns)==0) cat("All quadrats have between 0 and 100% fern cover. <br>") else {
     errorText("Quadrats without 0 to 100% fern cover:"); NiceTable(Quads_Percent_Ferns)}

cat("<br>**Quadrats Non-Living Percent > 100**<br>") 
  if(nrow(Quads_Percent_Overload)==0) cat("All quadrats have less than 100% summed tree, rock, CWD, FWD and other cover. <br>") else {
     errorText("Quadrats with over 100% summed tree, rock, CWD, FWD and other cover:"); NiceTable(Quads_Percent_Overload)}
```

---

### **Change Over Time**

### Quadrat Ground Cover Change
```{r Quads_Ground_Cover_Change, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Quadrats Tree Change > 10%**<br>") 
if(nrow(Quads_Percent_Trees_Changed)==0) cat("No records with an unusal change in Tree Cover.<br>") else {
   errorText("Events with a Tree Cover change of more than 10% between visits."); NiceTable(Quads_Percent_Trees_Changed)}

cat("<br>**Quadrats Rock Change > 10%**<br>") 
if(nrow(Quads_Percent_Rock_Changed)==0) cat("No records with an unusal change in Rock Cover.<br>") else {
   errorText("Events with a Rock Cover change of more than 10% between visits."); NiceTable(Quads_Percent_Rock_Changed)}

cat("<br>**Quadrats Bryophyte Change > 15%**<br>") 
if(nrow(Quads_Percent_Bryophytes_Changed)==0) cat("No records with an unusal change in Bryophyte Cover.<br>") else {
   errorText("Events with a Bryophyte Cover change of more than 15% between visits."); NiceTable(Quads_Percent_Bryophytes_Changed)}

cat("<br>**Quadrats Fern Change > 15%**<br>") 
if(nrow(Quads_Percent_Ferns_Changed)==0) cat("No records with an unusal change in Fern Cover.<br>") else {
   errorText("Events with a Fern Cover change of more than 15% between visits."); NiceTable(Quads_Percent_Ferns_Changed)}

```

---


