---
title: "Forest Vegetation Plot Floor QC"
author: "John Paul Schmit"
date: "5/19/2020"
output: html_document
---



```{r Plot_Floor_setup, include=F}

TotPlotFloor<-nrow(QCEvents) #Total number of plots being checked

Repeat_Plot_Floor<-QCEvents %>% group_by(Plot_Name) %>% summarize(Visits=n()) %>% filter(Visits>1) %>% pull(Plot_Name)

# The 2013 version is needed for deer impact as this was not measured pre 2013
Repeat_Plot_Floor_Post_2013<-QCEvents %>% filter(Event_Year>=2013) %>%  group_by(Plot_Name) %>% 
  summarize(Visits=n()) %>% filter(Visits>1) %>% pull(Plot_Name)

#3.1.0
Events_Bad_Rock_Cover<-QCEvents%>% filter(!Rock_Cover %in%  c( "<1", "1-5", "5-25", "25-50", "50-75","75-100")) %>% 
   select(Unit_Code, Plot_Name, Sample_Year, Rock_Cover)

#3.2.0
Events_Bad_Bare_Soil<-QCEvents%>% filter(!Bare_Soil_Cover %in%  c( "<1", "1-5", "5-25", "25-50", "50-75","75-100")) %>% 
   select(Unit_Code, Plot_Name, Sample_Year, Bare_Soil_Cover)

#3.3.0
Events_Bad_Trampled<-QCEvents%>% filter(!Trampled %in%  c( "<1", "1-5", "5-25", "25-50", "50-75","75-100")) %>% 
   select(Unit_Code, Plot_Name, Sample_Year, Trampled)

#3.4.0
Events_Bad_Deer<-QCEvents %>% filter(!(Deer_Impact==-1 & DeerImpactDescription=="Not Measured") &
                                     !(Deer_Impact==1 & DeerImpactDescription=="Very Low Impact") & 
                                     !(Deer_Impact==2 & DeerImpactDescription=="Low Impact") &
                                     !(Deer_Impact==3 & DeerImpactDescription=="Moderate Impact") &
                                     !(Deer_Impact==4 & DeerImpactDescription=="High Impact") &
                                     !(Deer_Impact==5 & DeerImpactDescription=="Very High Impact")
                                     ) %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Deer_Impact, DeerImpactDescription)


Events_Old_Deer <- QCEvents %>% filter(Event_Year<2013 & Deer_Impact!=-1) %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Deer_Impact, DeerImpactDescription)

Events_Missing_Deer <- QCEvents %>% filter(Event_Year>=2013 & Deer_Impact==-1) %>% 
  select(Unit_Code, Plot_Name, Sample_Year, Deer_Impact, DeerImpactDescription)

#3.5.0
Plot_Rock_Change<-if(length(Repeat_Plot_Floor>0)){
  QCEvents %>% filter(Plot_Name %in% Repeat_Plot_Floor) %>% 
  select(Plot_Name, Cycle, Sample_Year, Rock_Cover) %>% 
  mutate(Rock_Cover=factor(Rock_Cover, levels=c("<1","1-5","5-25","25-50","50-75","75-100"),ordered=T)) %>% 
  group_by(Plot_Name) %>% arrange(Plot_Name, Sample_Year) %>% 
  mutate(Start_Year=min(Sample_Year), Rock_Change=abs(as.numeric(Rock_Cover)-lead(as.numeric(Rock_Cover))) ) %>% 
  filter(any(Rock_Change>1)) %>% 
  pivot_wider(id_cols=c(Plot_Name, Start_Year), names_prefix = "Cycle ", values_from = Rock_Cover, names_from = Cycle)} else data.frame()

#3.6.0
Plot_Bare_Soil_Change<-if(length(Repeat_Plot_Floor>0)){
  QCEvents %>% filter(Plot_Name %in% Repeat_Plot_Floor) %>% 
  select(Plot_Name, Cycle, Sample_Year, Bare_Soil_Cover) %>% 
  mutate(Bare_Soil_Cover=factor(Bare_Soil_Cover, levels=c("<1","1-5","5-25","25-50","50-75","75-100"),ordered=T)) %>% 
  group_by(Plot_Name) %>% arrange(Plot_Name, Sample_Year) %>% 
  mutate(Start_Year=min(Sample_Year), Bare_Soil_Change=abs(as.numeric(Bare_Soil_Cover)-lead(as.numeric(Bare_Soil_Cover)))) %>% 
  filter(any(Bare_Soil_Change>1)) %>% 
  pivot_wider(id_cols=c(Plot_Name, Start_Year), names_prefix = "Cycle ", values_from = Bare_Soil_Cover, names_from = Cycle)} else data.frame()

#3.7.0
Plot_Trampled_Change<-if(length(Repeat_Plot_Floor>0)){
  QCEvents %>% filter(Plot_Name %in% Repeat_Plot_Floor) %>% 
  select(Plot_Name, Cycle, Sample_Year, Trampled) %>% 
  mutate(Trampled=factor(Trampled, levels=c("<1","1-5","5-25","25-50","50-75","75-100"),ordered=T)) %>% 
  group_by(Plot_Name) %>% arrange(Plot_Name, Sample_Year) %>% 
  mutate(Start_Year=min(Sample_Year), Trampled_Change=abs(as.numeric(Trampled)-lead(as.numeric(Trampled)))) %>% 
  filter(any(Trampled_Change>1)) %>% 
  pivot_wider(id_cols=c(Plot_Name, Start_Year), names_prefix = "Cycle ", values_from = Trampled, names_from = Cycle)} else data.frame()

#3.8.0
Plot_Deer_Change<-if(length(Repeat_Plot_Floor_Post_2013>0)){
  QCEvents %>% filter(Plot_Name %in% Repeat_Plot_Floor_Post_2013, Event_Year>=2013) %>% 
  select(Plot_Name, Cycle, Sample_Year, Deer_Impact) %>% 
  group_by(Plot_Name) %>% arrange(Plot_Name, Sample_Year) %>% 
  mutate(Start_Year=min(Sample_Year), Deer_Change=abs(Deer_Impact-lead(Deer_Impact))) %>% 
  filter(any(Deer_Change>1)) %>% arrange(Sample_Year) %>% 
  pivot_wider(id_cols=c(Plot_Name, Start_Year), names_prefix = "Cycle ", values_from = Deer_Impact, names_from = Cycle) %>% 
    arrange(Plot_Name)} else data.frame()

```

#### **Plot Floor Records Checked:** `r TotPlotFloor` ####


### Events with Plot Cover

---

### Rock Cover
```{r Rock_Cover, echo=FALSE, hold=FALSE, results="asis"}
if(nrow(Events_Bad_Rock_Cover)==0) cat("All events have a valid rock cover category.<br>") else {
   errorText("Events with missing or unrecognized an invalid rock cover category."); NiceTable(Events_Bad_Rock_Cover)}
```

---

### Bare Soil Cover
```{r Bare_Soil_Cover, echo=FALSE, hold=FALSE, results="asis"}
if(nrow(Events_Bad_Bare_Soil)==0) cat("All events have a valid bare soil cover category.<br>") else {
   errorText("Events with missing or unrecognized an invalid bare soil cover category:"); NiceTable(Events_Bad_Bare_Soil)}
```

---

### Trampled Cover
```{r Trampled_Cover, echo=FALSE, hold=FALSE, results="asis"}
if(nrow(Events_Bad_Trampled)==0) cat("All events have a valid trampled cover category.<br>") else {
   errorText("Events with missing or unrecognized an invalid trampled cover category:"); NiceTable(Events_Bad_Trampled)}
```

---

### Deer Impact
```{r Deer_Impact, echo=FALSE, hold=FALSE, results="asis"}
if(nrow(Events_Bad_Deer)==0) cat("All events have a valid deer impact and description.<br>") else {
   errorText("Events with missing or unrecognized an invalid deer impact or description:"); NiceTable(Events_Bad_Deer)}

if(nrow(Events_Old_Deer)==0) cat("No events prior to 2013 have deer impact recorded.<br>") else {
   errorText("Events prior to 2013 with deer impact recorded:"); NiceTable(Events_Old_Deer)}

if(nrow(Events_Missing_Deer)==0) cat("No events since 2013 have a missing deer impact.<br>") else {
   errorText("Events starting in 2013 with a missing deer impact."); NiceTable(Events_Bad_Deer)}


```

---



### **Change Over Time**

### Rock Cover Change
```{r Rock_Cover_Change, echo=FALSE, hold=FALSE, results="asis"}
if(nrow(Plot_Rock_Change)==0) cat("No records with an unusal change in Rock Cover.<br>") else {
   errorText("Events with a Rock Cover change of 2 or more between visits."); NiceTable(Plot_Rock_Change)}
```

---

### Bare Soil Cover Change
```{r Bare_Soil_Cover_Change, echo=FALSE, hold=FALSE, results="asis"}
if(nrow(Plot_Bare_Soil_Change)==0) cat("No records with an unusal change in Bare Soil Cover.<br>") else {
   errorText("Events with a Bare Soil Cover change of 2 or more between visits."); NiceTable(Plot_Bare_Soil_Change)}
```


---

### Trampled Change
```{r Trampled_Change, echo=FALSE, hold=FALSE, results="asis"}
if(nrow(Plot_Trampled_Change)==0) cat("No records with an unusal change in Trampled percent.<br>") else {
   errorText("Events with a Trampled percent change of 2 or more between visits."); NiceTable(Plot_Trampled_Change)}
```

---

### Deer Change
```{r Deer_Change, echo=FALSE, hold=FALSE, results="asis"}
if(nrow(Plot_Deer_Change)==0) cat("No records with an unusal change in Deer Impact.<br>") else {
   errorText("Events with a Deer Impact change of 2 or more between visits."); NiceTable(Plot_Deer_Change)}
```

---