---
title: "Forest Vegetation CWD QC"
author: "John Paul Schmit"
date: "5/19/2020"
output: html_document
---


```{r cwd_setup, include=F}


TotCWD<-nrow(QCCWD) #Total Number of events checked

#4.1.0
CWD_Bad_Transect<-QCCWD %>% filter(is.na(Transect_Azimuth) | !Transect_Azimuth %in% c(120,240,360) ) %>%
  select(Unit_Code, Plot_Name, Sample_Year, Latin_Name, Transect_Azimuth)

#4.2.0
CWD_Bad_Decay<-QCCWD %>% filter(is.na(Decay_Class) | !Decay_Class %in% c(1:5) ) %>%
  select(Unit_Code, Plot_Name, Sample_Year, Transect_Azimuth, Latin_Name, Decay_Class )

#4.3.0
CWD_No_Name<-QCCWD %>% filter(Latin_Name=="") %>% select(Unit_Code, Plot_Name, Sample_Year, Transect_Azimuth, Latin_Name)

#4.4.0
CWD_No_Diameter<-QCCWD %>% filter(is.na(Diameter)) %>% select(Unit_Code, Plot_Name, Sample_Year, Transect_Azimuth, Latin_Name, Diameter)

#4.5.0
CWD_Bad_Diameter<-QCCWD %>% filter(Diameter<7.5 | Diameter > 150 ) %>% select(Unit_Code, Plot_Name, Sample_Year, Transect_Azimuth, Latin_Name, Diameter)

#4.6.0
CWD_Bad_Hollow<-QCCWD %>% filter(!Hollow %in% c(TRUE, FALSE)) %>% select(Unit_Code, Plot_Name, Sample_Year, Transect_Azimuth, Latin_Name, Hollow)


```

#### **Pieces of CWD Checked:** `r TotCWD` ####

###  Transects
```{r Transects, echo=FALSE, hold=FALSE, results="asis"}

if(nrow(CWD_Bad_Transect)==0) cat("All pieces of CWD have a valid transect.<br>") else {
   errorText("Pieces of CWD with a transect other than 120, 240 or 360:"); NiceTable(CWD_Bad_Transect)}

```

---

### Decay
```{r Decay_Class, echo=FALSE, hold=FALSE, results="asis"}

if(nrow(CWD_Bad_Decay)==0) cat("All pieces of CWD have a valid decay class.<br>") else {
   errorText("Pieces of CWD with an decay class other than 1-5:"); NiceTable(CWD_Bad_Decay)}

```

---

### Species ID

```{r CWD_species, echo=FALSE, hold=FALSE, results="asis"}

if(nrow(CWD_No_Name)==0) cat("All pieces of CWD have a species ID.<br>") else {
   errorText("Pieces of CWD with no species name:"); NiceTable(CWD_No_Name)}

```


---

### Diameter

```{r CWD_Diameter, echo=FALSE, hold=FALSE, results="asis"}
cat("<br>**Missing Diameter**<br>")
if(nrow(CWD_No_Diameter)==0) cat(paste(TotCWD, " Pieces of CWD checked and all have a diameter.  \n")) else {
   cat("Pieces of CWD with no diameter:  \n"); NiceTable(CWD_No_Diameter)}

cat("<br>**Diameter too small or too large**<br>")
if(nrow(CWD_Bad_Diameter)==0) cat("All pieces of CWD checked have a typical diameter.<br>") else {
   errorText("Pieces of CWD with an diameter <7.5 cm or >150cm:"); NiceTable(CWD_Bad_Diameter)}

```

---

### Hollow

```{r CWD_hollow, echo=FALSE, hold=FALSE, results="asis"}

if(nrow(CWD_Bad_Hollow)==0) cat("All pieces of CWD checked ane entry for Hollow is valid.<br>") else {
   errorText("Pieces of CWD with an invalid entry for Hollow:"); NiceTable(CWD_Bad_Hollow)}

```


